### ISSUE TITLE
Improve styling on the volunteer roles page

### ISSUE THREAD

**Issue by SamLR** [emfcamp/Website#1036]
The page as it currently is is a long wall of text. We should try to make it clearer what's there and make browsing it easier. Possible solutions (probably one of these, not all)
* accordion styling for each role (i.e. only title is visible by default, when clicked on reveals the info)
* well/alternate background colour for job titles
* Table of contents
* Sub-pages (per team/area)?

specific roles should have anchors added so they can be found easily

**Comment by marksteward** [comment]
#1044 has done the well/alternative background colour part of this, I think we can probably park it for now.
