### ISSUE TITLE
Add lightning talks as a CfP Proposal type

### ISSUE THREAD

**Issue by SamLR** [emfcamp/Website#1037]
This will need to be another type. It will mostly operate for scheduling and planning so not used for e.g. full reviewing. 

Likely fields:

* title
* email (via login)
* short description 

These will be submit-able during the event (e.g. up until 2 hours before the session).

These will not make submitters legible to buy tickets.

**Comment by adventureloop** [comment]
I think we need slides with the submission, or a link to them. 

Does email include a public facing name?

**Comment by russss** [comment]
I wonder whether we just need something separate for this, as I'm not sure it has that much in common with the main CfP system

**Comment by SamLR** [comment]
> I think we need slides with the submission, or a link to them.

link would be easy (either as a dedicated field or just in the description). Embedding them would need to be implemented. What would be best? 

> Does email include a public facing name?

there is a name field, I'll add it to the ticket

**Comment by SamLR** [comment]
* slide link
* users with tickets only
* title/description
* time availabilty (day/morning evening pm)

further notes cc @adventureloop to check

**Comment by SamLR** [comment]
Process plan is this:

1. Lightning talk form will only be available once the schedule is fixed. This will mean we know how long each session will be
2. Users fill in the form selecting which session they want to be part of, if that session is already full raise an error
