### ISSUE TITLE
Can sign up to clashing shifts

### ISSUE THREAD

**Issue by ormiret** [emfcamp/Website#1077]
Get a warning message when signing up to a shift if the time overlaps another shift you're signed up to, but still seems to sign up for the clashing shift. 

Probably want the second signup to fail.

**Comment by jellybob** [comment]
Do valid use cases for signing up to two shifts at once exist? We'd probably want to discourage this, but there are probably some shifts that could be done in parallel such as info desk/volunteer manager as they're based in the same location (and realistically, mid-Sunday morning probably don't need full focus).

**Comment by ormiret** [comment]
I'd prefer system to default to not allow signing up to clashing shifts, but can allow admin (and maybe users if they click a "Yes, I'm doing this on purpose, I think I can cover both things" button) to override that for cases where we think it will work. 

I think most attempts to sign up to clashing shifts will be mistakes.
