### ISSUE TITLE
Check allow_comms_during_event before contacting anyone

### ISSUE THREAD

**Issue by ormiret** [emfcamp/Website#1081]
Want to only be considering people who've checked this for the various contact flows but could do with checking it for list of volunteers in  `volunteer_admin_notify.main` in case that filter gets forgotten anywhere. 

Do we need an override to send stuff even if they haven't checked `allow_comms_during_event`? For example if they've signed up for a shift and then it get's cancelled/moved/...

**Comment by russss** [comment]
I have no idea why this flag even exists, it doesn't really seem sensible to allow people to sign up as volunteers if we can't contact them.

**Comment by idnorton** [comment]
I asked this very question last night when we were doing triage through the tickets and checking on issues.

@ormiret pointed out that GDPR says opt-in for contact which is fair. I think we could argue that by signing up they're agreeing to be contacted during the event, and removing this simplifies sign-up, however not strongly enough to argue it too much :)

If we think we can reasonably change the position with this then perhaps this is the place to discuss that? If someone signs up on the volunteer desk to volunteer for a shift, it might be that they don't have the means to read the email address they give us?

**Comment by marksteward** [comment]
This is likely to get replaced with more granular notification preferences

**Comment by russss** [comment]
There's no GDPR reason to require this checkbox (in fact the relevant law here is PECR, which only covers marketing and advertising, which this is not). We should remove it.

To be very nice, we could just put a little note under the form saying why we'll email. But if you're signing up to volunteer I think it's pretty obvious that we'll need to contact you about that.

Perhaps it would be nice to have more granular notification options for when you want to be contacted about shifts, etc, but that's fairly minor and not necessary for this year.
