### ISSUE TITLE
Rid the ordering process of cookies

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#109]
REST all the things

**Comment by russss** [comment]
I don't think in theory that keeping the basket in session data is too bad a thing now we've slimmed the main payment flow down to two pages. 

The main remaining issue is if you're trying to buy tickets in two browser windows on the same session, you could be in a situation where /tickets/pay shows you one total, but you get a different total once you bounce to the payment processor.

I will commit a fix for this by verifying the basket total against a field on the page, and then I'm relatively happy to call this closed. (For now.)

**Comment by marksteward** [comment]
:+1:
