### ISSUE TITLE
Villages list is unusable on mobile phones

### ISSUE THREAD

**Issue by jellybob** [emfcamp/Website#1091]
The public village list at https://www.emfcamp.org/villages/2022 has content off to the right of the viewport, and doesn't support horizontal scrolling. Ideally it would probably be fully responsive, but at a minimum it should allow viewing all the content.

**Comment by marksteward** [comment]
Bodged by making the Field-FX URL wrap (1a78801). #1093 is the longer term fix.

**Comment by SamWatsonOrSomething** [comment]
Solid bodge, I like it.
