### ISSUE TITLE
Add a "change email address" admin feature

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#1092]
Also allow changing names, and show who created/edited a user.

**Comment by SamLR** [comment]
This has been implemented for changing the email associated with a CfP proposal https://github.com/emfcamp/Website/pull/1095 

I think this is still needed as they support different flows but might be useful to re-use the form or similar

**Comment by prehensile** [comment]
Following chat on IRC earlier, I agree we still need this for the same reason - they support different use cases.
