### ISSUE TITLE
"Reserve ticket for payment" expires too quickly

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#1105]
We have a "reserve ticket for payment" feature at `/admin/tickets/issue`. This puts a ticket in a basket and sends the user a payment link.

This appears to use the normal basket expiry time which is too short for email really. These baskets should have a longer expiry time (3 days sounds like a good number), and the time it expires should be shown in the email sent to the user.

**Comment by russss** [comment]
I think it's this expiry time, which is 3 days but is reduced to 1 hour when bank transfers are disabled (which is just a convenient way of recognising when it's close to the event):

https://github.com/emfcamp/Website/blob/b77afc368ba66ab8add00f5d9ee4a64f089a9ced/apps/tickets/tasks.py#L221-L230

In this case 3 days is OK, but 1 hour isn't.

I think the answer to this is probably to set the expiry time as an attribute of the Purchase.

**Comment by marksteward** [comment]
Fixed by 069a4d7
