### ISSUE TITLE
Set age range/family friendly flag on talks and workshops

### ISSUE THREAD

**Issue by SamLR** [emfcamp/Website#1110]

**Comment by SamLR** [comment]
This may get picked up as part of #1094

**Comment by jellybob** [comment]
Even if it does, some consistency in how age ranges are labelled would be good - the frontend is just going to provide a filter for every unique value found in that field.

**Comment by SamLR** [comment]
Notes from #1117 
    content warning - free text field so that the submitter can describe the warning
    child friendly - check box

**Comment by SamLR** [comment]
@Jonty for this I assume we can remove the existing 'age range' in favour of the simple checkbox for 'family friendly'?

**Comment by Jonty** [comment]
We still need age range on workshops
