### ISSUE TITLE
Save button for calendar feeds doesn't work

### ISSUE THREAD

**Issue by jellybob** [emfcamp/Website#1120]
Even if all you've done is preview, hitting the save button on an ical feed doesn't update the source URL.

**Comment by jellybob** [comment]
It looks like we're explicitly blocking updates in https://github.com/emfcamp/Website/blob/main/apps/schedule/external.py#L83-L85 - is there a reason for that? Presumably once a feed is approved for publishing it doesn't really matter if someone changes out the source URL for the feed because they could just go and replace everything in their feed and see it appear in the schedule anyway.

**Comment by marksteward** [comment]
That's the add, updates are https://github.com/emfcamp/Website/blob/main/apps/schedule/external.py#L142

**Comment by marksteward** [comment]
The save button works for me - were you getting a validation error maybe?

We should add a delete/disable button.

**Comment by jellybob** [comment]
The save button works, but it doesn't actually update the URL when I go back and view it again.

**Comment by marksteward** [comment]
Ooh, interesting...

**Comment by marksteward** [comment]
Should work now!
