### ISSUE TITLE
Ask for pronouns in CfP finalisation

### ISSUE THREAD

**Issue by Jonty** [emfcamp/Website#1124]
We've had instances of heralds using incorrect pronouns and upsetting speakers in the past, we should ask for preferred pronouns in finalisation and ensure the heralds have this information when introducing talks.

**Comment by Jonty** [comment]
This also implies that we have a view of the CFP for heralds with this information, as they won't have access to the CfP view and it feels weird to have this on the main schedule?

We could also give heralds cfp-viewer permission and have a now/next view they can easily pull from.

**Comment by marksteward** [comment]
Not to be confused with cfp_reviewer. I'd quite like to give all orga something like cfp-viewer so they can see what's going on.

**Comment by russss** [comment]
Can we get away with a public-but-unlinked now/next page for heralds? I don't think any of this info is private. Might be useful for video/AV people as well.

**Comment by Jonty** [comment]
I was about to suggest that but I figured we may also want to show the `requirements` field and I'm unsure if that might have private information in. We can do a pass to check this.

**Comment by SamLR** [comment]
Should be easy enough to make there's already a now and next public page so we can steal most of the code from that

**Comment by Jonty** [comment]
I've just noticed that Google I/O is exposing pronouns on speakers sometimes (presumably where they've been specified) so perhaps we should just allow people to optionally specify them and do that. Nice to make it clear to everyone?

https://io.google/2022/program/7f0f4d16-b260-414d-9f2d-bd2e18ea469b/

**Comment by SamLR** [comment]
Does it make sense to gather this as part of the diversity form (probably with a disclaimer that pronouns will not be used to infer gender etc). That way people only have to specifiy it once rather than as a property of a talk or similar?

**Comment by Jonty** [comment]
That is filled in at submission time so it's too late this year, but also if we're publishing it we should be asking them to verify it at finalisation time (which we also do with Name)

**Comment by idnorton** [comment]
Feels like the safest approach here would be to have Heralds ask the speaker immediately before introducing them.

**Comment by idnorton** [comment]
I'm re-titling the issue from `Ask for preferred pronouns in CfP finalisation` to `Ask for pronouns in CfP finalisation`.
