### ISSUE TITLE
Ask for examples of music/video for performances in CFP

### ISSUE THREAD

**Issue by Jonty** [emfcamp/Website#1125]
We currently don't ask for people submitting performances to submit samples of their performance (music/video), which makes a lot of them very hard to judge for quality. We need to do this.

**Comment by lukegb** [comment]
We actually do: https://github.com/emfcamp/Website/blob/03f97a498d8fd83605c39878bae8877369ea004f/templates/cfp/form_performance_include.html#L11-L12

but I guess we could make it clearer inside the form.
