### ISSUE TITLE
Update finalise email WRT HDMI requirements

### ISSUE THREAD

**Issue by SamLR** [emfcamp/Website#1137]
Because life is short (and video cables numerous) we'll be requiring all video/slides go via hdmi. [`templates/emails/cfp-please-finalise.txt`](https://github.com/emfcamp/Website/blob/main/templates/emails/cfp-please-finalise.txt) should be updated to reflect this

from IRC (@alfiepates)
>  I would like speakers to know that if they need to output video in a format other than HDMI, they are responsible for making this into HDMI for us

**Comment by russss** [comment]
Jonty says this will go in the final (manual) email to speakers - might be worth making a pad. I don't think it belongs in the finalise email.

**Comment by SamLR** [comment]
pad started and linked in content
