### ISSUE TITLE
Improve how lightning talks are handled

### ISSUE THREAD

**Issue by SamLR** [emfcamp/Website#1143]
cf. [#1136 ](https://github.com/emfcamp/Website/pull/1136#discussion_r874294636)

We should have a better way to either find the allocated lightning talk slots (rather than string matching) OR treat lightning talks as part of the main talk track that just have to be scheduled together by slot machine

**Comment by russss** [comment]
I forgot we had this one and added a slightly clearer explanation in #1151.
