### ISSUE TITLE
Venues should be configurable through the CfP admin interface

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#1149]
At the moment our main venues have to be added to the DB by a script. These should be configurable in the admin interface.

**Comment by jellybob** [comment]
They also need a lat/lng on them in order to place them on the map.

**Comment by lukegb** [comment]
I think this was mostly fixed by #1186; is there anything else needed here?

**Comment by lukegb** [comment]
There's still time ranges that should be configurable in the UI. I'm going to close this and open a separate issue for that.
