### ISSUE TITLE
Add 'issue ticket' button to admin/user

### ISSUE THREAD

**Issue by SamLR** [emfcamp/Website#1168]
Because there are a reasonable number of speakers & installation havers that we end up issuing multiple rounds of tickets to and it's easier than copying their email (continuing my quest for peak laze)

**Comment by russss** [comment]
It's already there!
<img width="1434" alt="Screenshot 2022-06-20 at 11 23 33" src="https://user-images.githubusercontent.com/45057/174581973-c23cf37f-a87d-4261-b825-8d76c17652b9.png">
