### ISSUE TITLE
maps.emfcamp.org CORS error silently prevents adding new places

### ISSUE THREAD

**Issue by saizai** [emfcamp/Website#1171]
https://map.emfcamp.org/ has a CORS error when adding a map point (click plus symbol button on right side), making e.g. village creation silently fail.

This is caused by PUT https://www.emfcamp.org/api/map/create at https://map.emfcamp.org/main.b80c8554a75665652fea.js prettified line 31921 (value of key "post_data"), with browser-default strict-origin-when-cross-origin policy. See https://developer.chrome.com/blog/referrer-policy-new-chrome-default/ (maps.emfcamp.org is not the same origin as www.emfcamp.org).

Also, preflight OPTIONS /api/map/create via h2 gives 404.

Not sure if both errors are blocking or just one.

**Comment by russss** [comment]
This is not finished yet.
