### ISSUE TITLE
Fix side-effects for GET requests

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#118]
gocardless_complete has side effects. We should really ensure it doesn't cause two emails to be sent, etc.

**Comment by russss** [comment]
I don't think the main payment flow has any GET side effects any more, the problems it still does have are covered by #109. Not sure what/where tickets_all_receipts is. Probably worth just changing this issue to apply to gocardless_complete, and then de-scoping it from this milestone.

**Comment by SamLR** [comment]
Do we still have side-effecting GETs?

**Comment by marksteward** [comment]
This is fixed since b82d0d5, as we now lock payments before changing them in gocardless_complete. There's still potential weirdness around the tryagain feature which should create a new Payment instead of reusing the same one. But that's not going to break by accident.
