### ISSUE TITLE
Live-in vehicle tickets are confusingly similar to parking tickets

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#1193]
The live-in vehicle ticket says "Parking ticket" at the top in large bold letters, and "Live-in vehicle ticket" at the bottom in much smaller letters.

This is confusing. It confused me. Live-in vehicle tickets should say "Live-in vehicle ticket" at the top.

We shouldn't change this for 2022 as we've already sent the tickets out and this would result in two different variants of tickets for volunteers to check, but it needs to be fixed for next time

**Comment by marksteward** [comment]
From Sam's notes the other night, we should also split out the template and mention:

- To minimise space used (~6mx8m is reasonably)
- Waste
- Parking (?)
- Don't throw away knives & forks (really? This might have leaked from the site meeting discussion)
