### ISSUE TITLE
Log who made a change to a proposal

### ISSUE THREAD

**Issue by SamLR** [emfcamp/Website#1201]
We have many more people interacting with proposals and we should track who made changes

**Comment by marksteward** [comment]
The versioning system does this - check `version.transaction.user`

**Comment by SamLR** [comment]
Reopening because I'm not sure this is always the case, e.g. (from local testing)

```python
In [1]: a = Proposal.query.get_or_404(1).versions
...
In [16]: a.versions[0].transaction.user

In [17]: a.versions[1].transaction.user
Out[17]: <User admin@test.invalid>

In [18]: a.versions[3].transaction.user

In [19]: a.versions[2].transaction.user
Out[19]: <User admin@test.invalid>
```

**Comment by marksteward** [comment]
And empty user means it was a system operation (e.g. slotmachine) or someone who wasn't logged in at the time. CfP submission includes creating a user, so they won't be logged in at the time.

**Comment by SamLR** [comment]
I think we'd want to log that too

**Comment by marksteward** [comment]
If you want to log slotmachine operations, you could have it set the current_user before it performs any DB changes. I think calling `flush` after `create_current_user` should fix the CfP side.

**Comment by SamLR** [comment]
reopening as I think we want to make this visible in the 'versions' view. Updating title to reflect that
