### ISSUE TITLE
Volunteer UI: difficult to sign up in mobile view on Android/Firefox

### ISSUE THREAD

**Issue by jayaddison** [emfcamp/Website#1235]
Working with a sample size of two user issue reports on this at the moment - it's possible this problem only occurs on old-ish versions of Android.

The "Sign up" / "Cancel shift" button is rendered in the rightmost column currently, and that is outside of the rendering frame in mobile web view.  Pinch to zoom out appears unavailable.

**Workaround**: Requesting the desktop version of the page will load a zoomable page render with the table rendered to fit the screen.

![offscreen-columns-android](https://user-images.githubusercontent.com/55152140/172041869-3cf4f7e9-0e3f-4ac5-9223-70992427ce2b.png)

**Comment by jayaddison** [comment]
NB: it's also possible to work around this by tapping on the row that the user would like to sign up to - this opens a modal dialog with a button that performs the same action as the column button.

**Comment by marksteward** [comment]
This doesn't seem to work :( Is it a Bootstrap 4 thing?
