### ISSUE TITLE
Volunteer role admin page improvements

### ISSUE THREAD

**Issue by sde1000** [emfcamp/Website#1242]
In addition to the list of shifts displayed on the volunteer role admin pages, it would be useful to have at the top of the page two lists of volunteers:

1. A list of people who we expect to arrive soon (say in the next 30 minutes) and who should already have arrived but haven't, with buttons for "they arrived" and "they didn't show up".
2. A list of people who have arrived for but not yet completed their shift, with buttons for "they completed the shift" and "they abandoned the shift".

**Comment by ormiret** [comment]
Now covered in #1319
