### ISSUE TITLE
"quick tasks" for volunteers

### ISSUE THREAD

**Issue by Jonty** [emfcamp/Website#1244]
A "quick tasks" list that any volunteer can look at and check things off, such as "check if all the toilets have toilet paper". Arguably this could be directly linked to c3bottles if we deploy it.

@Pezmc is keen on this for logistics tasks. It might even be useful during build/tear.

**Comment by marksteward** [comment]
Straw and furniture during teardown could go on this list, though it probably also needs calling out in the booklet/closing ceremony.

**Comment by russss** [comment]
I'm thinking of building a separate system for buildup/teardown, as I'm not particularly sure it would benefit from being linked to the main website, but we should definitely have a think about this.

We should also consider the difference between a "push" system (go and check the toilet paper in these toilets) vs a "pull" system (reporting that the toilet paper is low, a la c3bottles)

**Comment by russss** [comment]
Closing in favour of #1393 which has more detail.
