### ISSUE TITLE
schedule filter should have default view options preselected even for past events

### ISSUE THREAD

**Issue by sknebel** [emfcamp/Website#1247]
Right now https://www.emfcamp.org/schedule/2022 is by default empty, which is somewhat reasonable. But if I click the filter box and select "show past entries", I also need to fill out all the other filters to get entries to show, because by default they all are set to show nothing:

![grafik](https://user-images.githubusercontent.com/1082036/173203651-f3adf982-4062-4da2-8a80-193ae67ffe52.png)

I don't quite know how this looked during the event and have not yet reviewed the code - maybe it preselects based on future events (of which right now there are none)? Right now when trying to look back it is certainly confusing.

**Comment by marksteward** [comment]
Fixed by af34ba0
