### ISSUE TITLE
Make it MUCH clearer that we do not permit Q&A except in exceptional circumstances

### ISSUE THREAD

**Issue by Jonty** [emfcamp/Website#1256]
We need to repeatedly state this in the CFP submission process, right now people only get told this in finalisation.

We should perhaps add a checkbox for "I would like to take questions from the audience" or "this is an audience interactive session", so we can make exceptions for some of the panels or things that require participation.

We also need to make sure heralds know if they should be permitting it.

**Comment by russss** [comment]
Here's the problem:

https://github.com/emfcamp/Website/blob/main/templates/emails/cfp-slot-scheduled.txt#L23-L25
