### ISSUE TITLE
/static/icons/device-camera-video.svg has gone missing

### ISSUE THREAD

**Issue by davidc** [emfcamp/Website#1257]
/static/icons/device-camera-video.svg has gone missing, used in past year schedules like https://www.emfcamp.org/schedule/2016 and apparently time machine too.

**Comment by marksteward** [comment]
This should be brought in automatically from Octicons so something's gone wrong there. It should be referencing one of:

- https://www.emfcamp.org/static/icons/device-camera-video-24.svg
- https://www.emfcamp.org/static/icons/device-camera-video-16.svg

**Comment by marksteward** [comment]
Fixed by https://github.com/emfcamp/Website/commit/55c8a049ecf6af7afef14db12cf9194c2d344547
