### ISSUE TITLE
YouTube video embeds should be click-to-load

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#1298]
This is nice from a privacy perspective and also their embed JS is massive.

**Comment by lukegb** [comment]
Is there a good place to stick video thumbnails? I'm thinking it would be nice to display the video thumbnail with a little play button overlay, but it's sort of self-defeating if the thumbnails are being loaded from the YouTube CDN.

**Comment by russss** [comment]
We serve media.ccc.de embeds by default anyway (and they host the thumbails in that case) so youtube is only a fallback when the video isn't on media.ccc.de for whatever reason. So I think it's probably fine if youtube embeds don't have a thumbnail.
