### ISSUE TITLE
Volunteer manager features

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#1319]
Requested new features for volunteer managers:
- On the “role admin” page we want a list of people who have Arrived but not Completed, from all shifts
- Rather than passively leaving someone in the “Not arrived” state, we want to be able to mark them as “No Show”
- Perhaps have a list of “active” shifts - everyone signed up to a shift that has started who has not yet been marked as “arrived” or “no show”, and everyone who is arrived but not completed

Also want to summarise this information for the export.

**Comment by ormiret** [comment]
Had an old ticket for this: #1242 

I think description here is a bit clearer so keep this one and close old one.

**Comment by sde1000** [comment]
The "abandoned" shift state from #1242 could still be useful, as an alternative to "completed".

**Comment by wlcx** [comment]
> The "abandoned" shift state from https://github.com/emfcamp/Website/issues/1242 could still be useful, as an alternative to "completed".

This seems to exist already, unless I'm misunderstanding @sde1000 ? 
<img width="494" alt="image" src="https://github.com/emfcamp/Website/assets/3065381/c4e43a2d-c0e0-4ef6-ae05-75f921bc2f95">

**Comment by wlcx** [comment]
I'm a little confused about the existence of both `abandoned` and `completed` - are they not mutually exclusive?

> Rather than passively leaving someone in the “Not arrived” state, we want to be able to mark them as “No Show”

Similarly with this - are `arrived` and `no show` not mutually exclusive?

**Comment by wlcx** [comment]
That would seem more obvious to me with no context - trying to understand why it might not be sufficient?

My only guess was that managers forget to mark folks as arrived, which, if we used a boolean for arrived/noshow would mean false noshows?

**Comment by jellybob** [comment]
This does all feel like a single state to me. You can’t be arrived and a no show, and you can’t abandon or complete without arriving.

**Comment by wlcx** [comment]
Yep. I could see abandoned as a third state, where someone arrived and then disappeared mid-shift.. but is that common enough to track?

**Comment by sde1000** [comment]
@wlcx
> My only guess was that managers forget to mark folks as arrived, which, if we used a boolean for arrived/noshow would mean false noshows?

Exactly this. If someone is marked as "No show" we know it's because the bar manager took that action; the same with "Abandoned" or "Completed" and there's no further action to take with that shift.

A "not arrived" state means that the manager still needs to take action about the shift: has the volunteer turned up but not introduced themselves yet? Have they been shown around and set up on the tills? If they are a returning volunteer, did they show up and just start working straight away? Essentially, the list of "Not arrived" shifts is the manager's to-do list.

**Comment by russss** [comment]
I think it's just easier to store this in the state field rather than having boolean modifiers. Personally I think it makes more sense.

There's also a question of what you'd call a state which encompassed both "abandoned" and "completed", for example...

**Comment by wlcx** [comment]
Ok, I'm with you. I think we can only ever be in one of these states at once, so how would you feel about an enum rather than a bunch of booleans:

- Not arrived (initial, default)
- No show
- Arrived
- Completed
- Abandoned

**Comment by wlcx** [comment]
Ah, what @russss said. Though I can't see an existing state field - am I missing something?

**Comment by russss** [comment]
Oh, right, it *is* a set of booleans at the moment. I reckon it would simplify things if we move it to a state field.

We use [this pattern](https://github.com/emfcamp/Website/blob/main/models/cfp.py#L40-L59) in other places where you can set which state transitions are acceptable.

**Comment by sde1000** [comment]
...although if restricting the allowable state transitions, remember that the manager may sometimes mis-click!

**Comment by wlcx** [comment]
Ok, I think this answers my questions. Thanks all!

I was considering making the role admin page part of the bootstrap admin UI rather than the main website. Any objections?
