### ISSUE TITLE
Create method to add a user and proposal that goes straight to manual review

### ISSUE THREAD

**Issue by SamLR** [emfcamp/Website#1327]
When we invite speakers we don't want their proposals to go via the usual review process.

Proposed flow:

1. a CfP admin fills in a form (name, email, proposal type...)
2. the speaker gets an email with login link that redirects to the appropriate cfp form (e.g. cfp/talk), they fill it in
3. when submitted the proposal goes to the 'manual review' state (rather than 'new' etc)

in theory this can be done without using the db by setting query parameters etc (with some sort of verification) but it may just be easier to add yet-another-boolean to the row (or possibly the user) which indicates "this is an invited proposal|speaker move to manual review"

Another way to do this might be:
1. cfp admin fills in form which creates user + proposal (empty and already in 'manual review')
2. login email that forwards to /cfp/proposals/<id>/edit

I think this second option is probably better as any query params can be plain text etc. b/c they only make sense if a proposal already exists (and can be checked for validity when opening the page, e.g. if the param is `?manual_review=true` this arg is only kept if that's actually the state the proposal is in already.. also means manual review remains sticky as a state)

**Comment by russss** [comment]
I could have sworn I created this already as I spent a lot of time doing this last time for music but apparently I didn't...

#813 is related, although I think ultimately we probably need both features...

**Comment by russss** [comment]
Actually I think the first part of your proposal is #813, but we definitely do need a way for an admin to just add something directly.
