### ISSUE TITLE
Wise bank import does not populate payee name

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#1328]
Payee name was showing as "None" on the bank payment screen - these accounts were auto-populated by the Wise import function:

<img src="https://github.com/emfcamp/Website/assets/45057/0fea7e6a-5ed1-4f8d-a95d-59477ba6b115" width="300">

Additionally, the payment config screen (`/admin/payment-config`) does not show this problem.

We should:

* Import the payee name (presumably this is possible) or require manual entry
* Show the payee name on the payment config screen
* Prevent a bank account from being activated on the payment config screen if it doesn't have a payee name.
* Throw an exception in the payment flow if the payee name or any other required payment details are not present.

No issue for 2024, I've manually populated these in production.

**Comment by jayaddison** [comment]
Ok; we're pulling the incorrect field names here; the `title` field that we attempt to read from is from the new-format [`account-details` API](https://docs.wise.com/api-docs/api-reference/bank-account-details); previously the relevant field was, I think, named `accountHolderName` in the [(now-deprecated) `borderless-accounts` API](https://docs.wise.com/api-docs/api-reference/deprecated).

This would require an update to `pywisetransfer`.

**Comment by jayaddison** [comment]
Closing - I believe this was fixed by #1329.
