### ISSUE TITLE
2024 privacy policy review

### ISSUE THREAD

**Issue by lukegb** [emfcamp/Website#1339]
Things I noticed, offhand:

- Mentions MailChimp (which I think is no longer in use)
- Mentions Helpmonks (which I think is being migrated off of? are there any mailboxes remaining on helpmonks?)
- Mentions the EU-US Privacy Shield (should be updated to the US Data Privacy Framework and the UK Extension to the EU-U.S. DPF)
- media.ccc.de link is broken

**Comment by lukegb** [comment]
Stripe's DPF statement is at https://stripe.com/gb/legal/data-privacy-framework; don't know if there are any _new_ 3rd party providers (I assume not, given the trend has been to selfhost more things rather than fewer)

**Comment by russss** [comment]
I had all these changes done and then they collided with moving everything to markdown :/ I should finish porting them over.
