### ISSUE TITLE
wiki links no longer work

### ISSUE THREAD

**Issue by alifeee** [emfcamp/Website#1367]
Hi. I looked on the 2022 wiki a lot, at the villages. For inspiration.

The wiki no longer is active, and `wiki.emfcamp.org` redirects to `www.emfcamp.org`.

is this intentional?

example wiki pages:

![image](https://github.com/emfcamp/Website/assets/13833017/3bf82384-4094-4a6b-81fe-0a06475a4e88)

example wiki page URL:

<https://wiki.emfcamp.org/wiki/Category:Villages>

**Comment by wlcx** [comment]
FWIW wikis from previous years are archived: https://wiki-archive.emfcamp.org/2022/wiki/Electromagnetic_Field_2022

**Comment by russss** [comment]
There will be a new wiki live soon - the old one is archived as @wlcx mentioned. We should put a year in the URL this time to make this less ugly.

**Comment by alifeee** [comment]
radical, that's good to know. I will wait for search engines to catch up :)
