### ISSUE TITLE
Create a non-admin view of users

### ISSUE THREAD

**Issue by SamLR** [emfcamp/Website#1371]
when a cfp_admin clicks on a user in a proposal they should get sent to some sort of useful view.

This should show all that user's:
* proposals
  * + message status (& note counts) for their proposals
* email address
* cfp_invite_reason
* Whether they have a ticket
* arrival time if given?

If the a user_id that doesn't have any proposals is set the page should 404

**Comment by wlcx** [comment]
Closed by #1372 unless anything was missed @SamLR ?
