### ISSUE TITLE
Show ticketholding status of submitter on proposal view

### ISSUE THREAD

**Issue by Jonty** [emfcamp/Website#1381]
When reviewing proposals that are manually accepted (e.g. on Installations) it would be useful to be able to see if the submitter already has a ticket, as we default-accept most things that have no cost and the submitter is already attending.

**Comment by marksteward** [comment]
Added to the proposal page with b77afc36 - does that work?

**Comment by wlcx** [comment]
I'd say so? Looks like this:

<img width="950" alt="image" src="https://github.com/emfcamp/Website/assets/3065381/b69b824b-12d6-4573-9853-db629d3822c7">
