### ISSUE TITLE
Join user info into proposals export

### ISSUE THREAD

**Issue by jonathanhogg** [emfcamp/Website#1404]
It'd be good for reconciling against Other Things to be able to export all of the installations proposals with the user info (name and email address basically, though "has ticket" might also be a useful thing).

Current export just puts the ID in with no obvious way that I can see for getting that info through an alternative download. [I may just be missing another button, but I am generally wary of pressing anything I don't understand in the CFP system…]

**Comment by lukegb** [comment]
Fixed in #1423.
