### ISSUE TITLE
Ticket should only have one barcode on it

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#1445]
We currently have both a 1D and a 2D barcode on the ticket. I think we've historically scanned the 1D barcode.

This confuses people because they're now used to using 2D barcodes on tickets, and they will default to showing us that. (The 1D barcode also seems to be where people fold the ticket.)

We should settle on one type of barcode (probably the 2D one, which is more convenient for showing on phones) and get rid of the other one.

**Comment by will-h** [comment]
QR codes actually seem to scan better than Code128 on Honeywell Xenon 1500 barcode scanners. EMF2022 ticket QR code zoomed to 20mm across on a phone screen scan at 300mm distance, so I think we're good there. Might be worth putting the barcode at the top left of the PDF.

ms7821 would like to use more mobile devices which would probably be easier with QR codes too.

**Comment by marksteward** [comment]
1D barcodes removed with f3863a2
