### ISSUE TITLE
Edit note about fire on the "what to bring" page

### ISSUE THREAD

**Issue by mscroggs** [emfcamp/Website#1461]
On https://www.emfcamp.org/about/what-to-bring it says under "do not bring": "Things that are on fire: Unless you've cleared them with us beforehand."

Someone in my village has interpreted this as "camping stoves are banned". We should edit this to be clearer, eg "Anything other than a small camping stove that is on fire."

**Comment by marksteward** [comment]
We already say camping stoves are allowed, but I did spot this previously and wonder whether we should remove it as not everyone's aware of the in-joke,

**Comment by mscroggs** [comment]
You're right, I should have read the rest of the page more clearly. I agree that removing it probably causes the least confusion
