### ISSUE TITLE
Update role admin page

### ISSUE THREAD

**Issue by jellybob** [emfcamp/Website#1524]
From Steve, but this seems a reasonable template for all roles:

* A list of people who have Arrived but not Completed, from all shifts (i.e. everyone who is supposedly still working at the bar)
* A list of “active” shifts - everyone signed up to a shift that has started who has not yet been marked as “arrived” or “no show”
* A list of "next" shifts - so we can see whether we are supposed to get new staff at shift changeover time, or whether we are supposed to panic and shout out for more volunteers on the socials...

A combination "todo" list, for marking off people as they arrive, and a "how is the next couple of hours looking?" info page

**Comment by sde1000** [comment]
See also #1319

**Comment by jellybob** [comment]
And closing again, as this already exists.
