### ISSUE TITLE
Broken "guidence on setting up a feed of events" link

### ISSUE THREAD

**Issue by gbaman** [emfcamp/Website#1533]
Looks like the following link is broke, as I'm assuming pointed to a page on the 2022 wiki which is no more.
https://github.com/emfcamp/Website/tree/main//templates/schedule/external/feeds.html#L8
(link itself is https://wiki.emfcamp.org/wiki/Publishing_Village_Schedules)

From https://www.emfcamp.org/schedule/publish page

![image](https://github.com/emfcamp/Website/assets/833193/d5051684-c8e3-40b4-b67f-e5f339b29f67)

**Comment by jellybob** [comment]
That functionality shouldn't have been visible at all, and is now disabled.
