### ISSUE TITLE
Topic survey should not have defaults selected

### ISSUE THREAD

**Issue by Jonty** [emfcamp/Website#1539]
The [topic survey](https://github.com/emfcamp/Website/blob/a9760428206fd3812fbff883eaf03f4b6f63e56d/templates/_diversityform.html#L23) for reviewers currently has defaults of tag 1/2/3 in the tag list, which means we are going to end up with a bias towards "accessibility", "ai", and "alternative".

We should make these default to empty.

![image](https://github.com/emfcamp/Website/assets/1553/3cc529b2-b696-4ef2-a3b7-9334ec1e6274)

**Comment by marksteward** [comment]
Fixed by #1544
