### ISSUE TITLE
Venue allocations for attendee content get re-venued 

### ISSUE THREAD

**Issue by SamLR** [emfcamp/Website#1556]
content that has been converted to attendee content (e.g. Karaoke) can't be set correctly to e.g. workshops

**Comment by mscroggs** [comment]
For example: https://www.emfcamp.org/cfp-review/proposals/542?show_user_scheduled=True should be in FieldFX

**Comment by marksteward** [comment]
Caused by https://github.com/emfcamp/Website/blob/main/models/cfp.py#L648-L650

**Comment by marksteward** [comment]
Hmm, this shouldn't actually matter, because the scheduler currently ignores user-scheduled content. So you can just ignore the list of allowed_venues and set the potential/scheduled venue by hand.

**Comment by Jonty** [comment]
This is still actually an issue according to Katie, will try and look at it today.
