### ISSUE TITLE
Light Mode on Website

### ISSUE THREAD

**Issue by davepage-mcr** [emfcamp/Website#1641]
Hi there,

My partner is visually impaired and finds the EMFCamp website very hard to read and use. This means he's missing out on opportunities to engage with and contribute to EMF.

Would it be possible to implement a choice of switching the website to a theme with dark text on a light background? Work-arounds such as viewing the site in "print mode" don't facilitate interaction.

Thanks!

**Comment by russss** [comment]
Thanks for the feedback! Unfortunately adding a different colour theme is quite a lot of work - we certainly won't have time to add it for this event, and I don't think we can really commit to maintaining two colour themes in the long term at this point either.

For what it's worth, the website does meet the [WCAG guidelines](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html) for minimum contrast (with one or two exceptions I just spotted and will try to get fixed). Not trying to diminish your partner's experience here, but we do take this seriously. 

Personally I think the light-on-dark design is getting a bit tired and my preference is to try and move towards a dark-on-light theme for our next redesign. So we will definitely take this into account then.

**Comment by davepage-mcr** [comment]
OK. As a workaround, I've tried creating some CSS overrides which I've published at https://userstyles.org/styles/274421

Perhaps this issue should be marked as a 2026 wishlist item?
