### ISSUE TITLE
Potential mark-as-read messaging bug when CFP reviewers have submissions

### ISSUE THREAD

**Issue by Jonty** [emfcamp/Website#1646]
From Will Furnell:
> I’m not 100% sure but I think there might be a bug with the CFP system where if the submitter of the proposal has CFP review access the messages are immediately marked as read. I think this may have happened to myself and a couple of members of the youth team. I haven’t confirmed this though.

I've not had chance to validate this, filing a ticket so we don't forget.

**Comment by marksteward** [comment]
Yep, confirmed.

**Comment by lukegb** [comment]
Yes; `def is_user_recipient` will return true if the proposer is an admin and the message is to an admin.
