### ISSUE TITLE
Suggestion: Sticky day labels on schedule page

### ISSUE THREAD

**Issue by gcsalzburg** [emfcamp/Website#1650]
Would be great when scrolling if the day was sticky to the top of the screen.

Use case: I'm continually scrolling up and down to work out what day something is on (and thus if I'll be there to see it). Especially as I browse the list by page-search for a keyword often. The workshop and talk times are very clear, but the days all blur together on such a long page.

**Comment by gbaman** [comment]
Agreed, there's just so much content in the schedule this year, it's very easy to mix up the days by reading the schedule. 
A simple quick fix answer might be just adding it alongside the time text?
I'm assuming it's coming from [here](https://github.com/emfcamp/Website/blob/main/js/schedule/Calendar.jsx#L147)?

Some options

<img width="791" alt="image" src="https://github.com/emfcamp/Website/assets/833193/7015e411-c969-4310-b832-b7688b6c72f3">.  
   
   
<img width="887" alt="image" src="https://github.com/emfcamp/Website/assets/833193/26ed56a9-4cda-4d07-9881-4a433fdf53ca">

   
   

<img width="888" alt="image" src="https://github.com/emfcamp/Website/assets/833193/ad632444-8909-43a4-8746-234a88f671ed">

**Comment by marksteward** [comment]
Done with 4734c081. I can't work out exactly why zooming in breaks it, but maybe that's a good thing.
