### ISSUE TITLE
Lightning talks CfP is hidden but open

### ISSUE THREAD

**Issue by unknowndomain** [emfcamp/Website#1659]
You can't get to the CfP for Lightning talks, which are apparently still open, page looks like this:

<img width="1004" alt="Screenshot 2024-05-26 at 21 47 42" src="https://github.com/emfcamp/Website/assets/147143/4c4ca9d8-1801-4b21-a0aa-bf1869becc94">

**Comment by marksteward** [comment]
Thanks, I've updated the notice to mention installations. We'll be changing how this works next year.
