### ISSUE TITLE
Make sure we get a proper error when tickets run out

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#166]
https://twitter.com/hifromkatie/status/473450487510237184

**Comment by russss** [comment]
Punting this to #192.

**Comment by marksteward** [comment]
The important bit here is initial rounds - we need to add a breaker that can change site state to sold-out before the productgroups are fully expired so we're not left with a group of annoyed people who can't buy the last 1 or 2 tickets. #192 can then send notifications when it doesn't affect site state.

**Comment by marksteward** [comment]
We throw "Not a valid choice" on the form for any tickets that have been exhausted, and don't redirect anywhere unless the site state has been changed from unavailable.
