### ISSUE TITLE
Separate payments from baskets

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#175]
A Stripe payment that fails after charge() will be given a chargeid, which will hit the webhook. However, we don't want to make these users rebuild their basket.

Attach tickets and payments independently to a basket, and allow a new payment method to be attempted once all payments for that basket have been failed/cancelled.

**Comment by russss** [comment]
I think given that we've massively reduced the amount of effort needed to order tickets, getting users to rebuild their basket is not a huge deal any more. This might still be a nice-to-have but I don't think it's blocking sales. What do you think?

**Comment by SamLR** [comment]
I think it's no longer blocking.

**Comment by marksteward** [comment]
Users no longer have to rebuild baskets as their tickets are reserved on the fly, and all the basket logic is now separated out. Cloning an existing payment is easy to add if we need it.
