### ISSUE TITLE
Add informal activities to CFP

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#180]
> We will also be opening up the CFP to allow people to register informal meetings and activities outside the main stages and workshops, so you could organise a python meetup in the bar and then register it so all EMF attendees know its happening.

**Comment by SamLR** [comment]
Should not be done via CfP but access to the schedule should be organised. Possibly via an iCal feed.

**Comment by marksteward** [comment]
Removed from milestone, but keeping open for discussion.

**Comment by marksteward** [comment]
This was done via the external ical feed.
