### ISSUE TITLE
Make sure declined Stripe payments work properly

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#203]
One this evening just kept going to tryagain. Another weird decline type?

**Comment by marksteward** [comment]
See also #175 and #152

**Comment by marksteward** [comment]
Using 4000000000000341 does this - https://stripe.com/docs/testing

**Comment by russss** [comment]
Yeah with those details on emfcamp-test.org I'm getting this:

![image](https://cloud.githubusercontent.com/assets/45057/11769886/d8271410-a1e9-11e5-8247-49a8ed23863f.png)

I'm going to milestone this and try and sort it tonight.

**Comment by marksteward** [comment]
I think offering to retry is probably the right thing to do. The error message is arguably inaccurate, but nobody's going to retry forever.

**Comment by russss** [comment]
Yeah, this is "as designed" because all the "try again" button does is attempts the charge again, which will fail.

We know the payment didn't succeed here, so we should probably improve the error messaging at least.

**Comment by russss** [comment]
In fact, I think retrying in this case is completely spurious as it's highly unlikely that the card will accept the exact same charge a second time if it failed the first time. My expected situation here would be to bounce back to the payment dialog again.
