### ISSUE TITLE
Expensing by attendees

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#204]
Feedback by email from someone wanting to get work to pay. They suggested a "who we are" section, as their work were uncertain about what kind of organisation we are.

There's also been concern that we brand ourselves as a festival, rather than a conference. Some wording that places our talks along that line might help, as there are conferences that would cover a subset of what we offer. Apparently this also affects tax in the Netherlands.

**Comment by davidc** [comment]
Is this not covered by https://www.emfcamp.org/about/company which is linked from the bottom of each page?

**Comment by marksteward** [comment]
Nah, they wanted more of a "here's who you're giving money to"

**Comment by marksteward** [comment]
On reflection, the wiki-archive, twitter account and media coverage are more than enough for this. Tax in the Netherlands is irrelevant.
