### ISSUE TITLE
Make sure templates, DB, etc. work with very long GCIDs

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#209]
```
From 1st June 2015 new IDs may be generated with up to 255 characters
```

We should elide the GCID when it's too long (in the gcid formatting function), and make sure nothing weird happens at 255 chars.

**Comment by russss** [comment]
|'ve removed GCIDs from a most user-facing places while sorting out the web site - I don't think we need to expose them. So I'd consider this closed.
