### ISSUE TITLE
Allow attendees to use the workshop management system

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#213]
To allow people to sign up to a personally-run workshop/session, get an idea of interest, money, etc.

**Comment by SamLR** [comment]
I think this should mostly be a method by which villages can flag that they're running a workshop (plus when and where). There doesn't seem to be a sane method of 'ticketing' workshops and 'first come: first served' seems the best solution.

**Comment by SamLR** [comment]
Closing this as I think this is now covered with feed import to the schedule etc.
