### ISSUE TITLE
Tickets - tick box for photography

### ISSUE THREAD

**Issue by Chaoticeunoia** [emfcamp/Website#226]
Request a tick box for to be photographed or not to be photographed. Including consent from parents to photograph children's activities. & if not to be photographed is ticked, then I will need some sort of visual confirmation ie lanyard to be worn

**Comment by marekventur** [comment]
Does that need to be part of the ticketing process or can we just have two different type (colour?) of lanyards for when people arrive?

**Comment by marksteward** [comment]
I think it's worth making sure people are aware in advance of the event, as asking them a question they're not expecting will slow down the arrivals process. I guess they don't need to make that decision in advance, but it will help us decide how many of each colour to get (if that's how we're doing it).

**Comment by SamLR** [comment]
If we offer this as an option how are we going to police it? How are we going to make it clear to people what constitutes being in a photo?

I think this is a good idea but I'd rather poll people after the fact but have a clear idea of what it all means than add a checkbox without clear guidance of what people can expect from it

**Comment by SamLR** [comment]
If this is something we're going to do then it'll be done via lanyards etc on site. Does not need sign up
