### ISSUE TITLE
Add navigation to talks

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#227]
https://www.emfcamp.org/talks currently redirects to /talks/2014, with no way to find /talks/2012. Add navigation of some sort (dropdown/left & right arrows).

NB this page is already referenced on Wikipedia.

**Comment by Paul2d** [comment]
Could this be redirected to /line-up for 2016? (or at least merged for the future as I think /talks is now superseded by line-up as a more accurate title)

**Comment by Jonty** [comment]
@Paul2d Fixed in cf08439, but not yet deployed.

**Comment by marksteward** [comment]
But it doesn't fix the ticket.

**Comment by SamLR** [comment]
I believe this is now fixed by b01f03e48
