### ISSUE TITLE
Make sure it's possible to buy free tickets

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#230]
If all tickets are free, or (perhaps in the future) we know they've already paid, make it possible to complete the checkout process without a balance.

**Comment by SamLR** [comment]
This also applies to U-5's ticket if bought without an adult (e.g. adding to an existing ticket)

**Comment by marksteward** [comment]
(Note: it's possible for admins to do this as a workaround since 159fc4b)

**Comment by marksteward** [comment]
Had to use the workaround after someone got stuck - this is no longer Nice-to-have.

**Comment by marksteward** [comment]
This is now #591
