### ISSUE TITLE
Fix flash for pre-existing user

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#235]
To take #225 into account, we need to make it easier for users who are already in the system. Make "log in" link to the login page, and explain about the email we'd have sent

**Comment by marekventur** [comment]
Done in #252

**Comment by marksteward** [comment]
Needs to be done for ticket flow, too (ideally inline).

**Comment by SamLR** [comment]
Done in ticket flow in #254

**Comment by SamLR** [comment]
Closing as #254 has been merged
