### ISSUE TITLE
Fix default button on ticket info form

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#236]
This is currently the Change Tickets button - it should be continue instead.

**Comment by marekventur** [comment]
This is not as easy as I was hoping it would be, the first button is the DOM is the one used as default. Tabindex doesn't seem to fix this. There are hackish workarounds, like switching the order and using floats to move them around in CSS again or creating an invisible button at the beginning. Thoughts?

**Comment by marksteward** [comment]
Looks like an input type="reset" doesn't become part of this game (although input type="submit" and button seem to have the same behaviour).

**Comment by marksteward** [comment]
Changing this to an <a> because we don't save the form properly, and now throw an exception if the email is invalid.

**Comment by marksteward** [comment]
Fixed by 8a0b500
