### ISSUE TITLE
Email-list generation

### ISSUE THREAD

**Issue by SamLR** [emfcamp/Website#244]
It should be possible to export lists of email addresses from the database that we can then contact. These lists will need to be filterable on a variety of attributes. This should only be accessible to admins.

The main attributes that will need to be filtered on are (but not only).
Whether the user:
* has a ticket
* is a ticket purchaser (or someone who has been transferred one)
* has a ticket of a certain type (e.g. caravan)
* has a ticket in a certain state (e.g. paid, cancelled etc.)

**Comment by marksteward** [comment]
Not sure this should be exportable. We want to contact people individually and automatically at the following points:

 - acquire a ticket (including from transfer)
 - transfer a ticket
 - ticket paid
 - 

and in bulk for things like:

 - EMF's in a week - here's what you need

I think this is best done as a util script (command)

**Comment by marksteward** [comment]
Fixed by Russ with d783741. I don't think we need to target caravan owners.
