### ISSUE TITLE
Fix TicketAttrib boolean coercion

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#245]
We should store booleans as a well-known value, or in a different table/column.

This should not exist: https://github.com/emfcamp/Website/commit/beb24de

**Comment by marekventur** [comment]
I've went through the code and I couldn't find a place where those two different values could come from. Any pointers?

**Comment by marksteward** [comment]
If you're using sqlite, adding a TicketAttrib set to True will insert a 1 (thanks to SQLAlchemy), but the column type is string so it'll come back out as "1". The same happens for postgres with t and "t",

**Comment by marksteward** [comment]
Maybe the easiest thing to do is change accessible to a boolean attribute on Ticket.

**Comment by marksteward** [comment]
This is being deleted. No longer a concern.
