### ISSUE TITLE
Detailed admin transfer view

### ISSUE THREAD

**Issue by SamLR** [emfcamp/Website#259]
The current admin view for ticket transfers only lists the type of ticket, who it was transferred from and to whom. There are several improvements that can be made on this.

At the minimum the admin view should allow the cancelling/reversal of a transfer in case of user error.

The admin should also be able to track transfers at a ticket level, i.e. see all the transfers that have happened to a single ticket in order. Tickets should also be linkable to the purchaser from this screen.

**Comment by wlcx** [comment]
Partially covered by #1378 - the transfer view can now be filtered by ticket id, linked to from the admin user page's ticket table.

I wonder perhaps if what we really want is a "ticket view" showing a single ticket, it's transfer history and current status. Would that then remove the usefullness/need for the "transfers" view?
