### ISSUE TITLE
Browser testing for payment flow

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#264]
We should test buying a ticket on GoCardless and Stripe on multiple browsers.

**Comment by SamLR** [comment]
I've tried this out on:

* On Mac
  * Chrome
  * Safari
  * Firefox
  * Opera
* On Windows 10 VM
  * IE 11
  * IE 9 (emulated in IE11)
  * Edge

Worked reasonably in all of them other than a problem due to flex-boxes in IE11 which is (I think) fixed in (706b39a7248ac741c8c3421decc02b493d8176c5)

**Comment by russss** [comment]
Seems legit, thanks!
