### ISSUE TITLE
Recolour btn-success and btn-primary

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#271]
I find myself using btn-success because btn-primary is close to invisible. Change btn-primary to be a more visible colour and switch to it where appropriate.

**Comment by russss** [comment]
I'll sort this out when Jake and I do the design refresh, but I'm beginning to move towards saying that if we keep the dark-blue background, all buttons need to be on a lighter-coloured area (a well or a panel) anyway.

**Comment by marksteward** [comment]
btn-primary is now a delightful plum.
