### ISSUE TITLE
Move non-website services off Gauss

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#281]
512MB is not enough for anyone.

**Comment by davidc** [comment]
It's been noted that the requirement for PHP (e.g. for wiki) is causing grief, I'd rather move the website to a new server that isn't running anything else at all (including DNS) - just database and web server. I can set up a new VM.

**Comment by russss** [comment]
We're going to keep the website on gauss (which is getting a RAM upgrade) and move everything else off.

**Comment by russss** [comment]
Moved wiki, wiki-archive, and the badge wiki off gauss onto Lorentz. What remains is BIND, mail services (inc mailman), and the main site.

We've also just been upgraded to 2 cores and 1GB RAM. Benchmarking indicates this should support a significant more traffic than we saw in December, and fail more gracefully.
