### ISSUE TITLE
Fix CfP logic while it's fresh

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#284]
43779b6^..68811b2 relies on the CfP opening after tickets, but there's no guarantee we won't open CfP before tickets next year.

**Comment by SamLR** [comment]
The core risk here is on the login page which is currently flagged using TICKET_SALES a possible solution may be to move the login functionality under its own flag to enable it with either sales or cfp.

**Comment by SamLR** [comment]
I think 9abfb17 closes this
