### ISSUE TITLE
Check what happened to any "new" payments

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#285]
They're probably due to us restarting the app. Contact them directly?

**Comment by SamLR** [comment]
This may be due to people abandoning stipe payments

**Comment by marksteward** [comment]
Yep, ditto GC payments that were abandoned. I'm going to close this and note that we should consider "new" state the same as "cancelled". Maybe at some point we'll rework the state flow so that "new" payments don't even get inserted into the DB.
