### ISSUE TITLE
Clearer EUR/GBP signposting 

### ISSUE THREAD

**Issue by will-h** [emfcamp/Website#290]
At least two people got confused and selected GBP tickets when they wanted EUR, at least one has tried to do a SEPA xfer into our GBP account. Typical complaint is 'The email didn't have any IBAN' etc.

So we should improve the signposting to let people swap currencies. 'this is a GBP payment. paying from Eurozone? Click here'...

**Comment by russss** [comment]
![image](https://cloud.githubusercontent.com/assets/45057/12216265/9c906dd0-b6d3-11e5-9b88-bd48d9a223ee.png)
