### ISSUE TITLE
CfP admin - make it easy to categorise/tag talks

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#294]
Admins should be able to tag talks as they come in, so the talks can be split up to the appropriate reviewer

- [ ] Add a select2/chosen/etc input and store the categories on the DB
- [ ] Add a search by tag page

**Comment by SamLR** [comment]
I don't think we need something like select2 for reviewing. Talks should only be in 1 category (although reviewers may be in several) and there should only be a few categories. Also select2 is the devil

**Comment by marksteward** [comment]
Category can be limited to one per talk, but I think we should provide some flexibility with filtering by tag. I don't want to get to a state where this is all dumped into a spreadsheet again because there's no way to group similar talks on short notice.

**Comment by Jonty** [comment]
No longer relevant (at least for now)
