### ISSUE TITLE
Allow talk editing by admins and submitters

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#295]
Admins and the original submitter should be able to edit any field in a CfP submission, but it should be audited (see #273).

**Comment by SamLR** [comment]
The original submitter should only be able to edit the submission within a 48 hr window of the receipt of the submission. The reason for this is to get a locked form of the submission that can then be passed on for anonymisation without unknown time limits.

This doesn't (have) to be versioned but from then on changes should be auditable.

**Comment by marksteward** [comment]
Fixed by 9998f8a
