### ISSUE TITLE
CfP Workshop copy

### ISSUE THREAD

**Issue by SamLR** [emfcamp/Website#300]
The copy for the workshops (either inline, on cfp page or on the guidance page) needs to make clear:

* Whether the submitter will need facilities from us
* If they're running with their own facilities if there are any requirements from us (or things we should know)
* That if there are no requirements on us that running via a village is a viable (arguably preferred) alternative).

**Comment by russss** [comment]
I think it's going to be difficult to convey all this info on the actual CfP form. I also don't know if it's necessary for the submitter to know about these technicalities in advance (it's likely that people who know about villages and want to hold their workshop there won't be hitting the CfP anyway). I added a mention in 1cc21f4.

I think the best approach here is for us to pick out workshop CfPs which would be better-suited to villages and let the submitter know.
