### ISSUE TITLE
Inline CFP help

### ISSUE THREAD

**Issue by SamLR** [emfcamp/Website#304]
The relevant help for the CFP forms should be available with the form. This should be short and convey only the required information.

The forms should also be organised to make it clear what information is being anonymised, who can see it and what it's being used for.

Placeholder text should not be relied on.

Specific note: 'requirements' should make it clear what will be supplied. I.e. laptop (although user's own is preferred), projector (+ VGA/DVI cables & mac adaptors), stage.

**Comment by russss** [comment]
I think we have the right balance of inline help now, and it's easy enough to add more later if we need it.
