### ISSUE TITLE
Be more clear that we give out free tickets for carers

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#307]
I don't think we say this anywhere now we've removed the accessibility checkbox.

**Comment by SamLR** [comment]
proposed text: 
"Accessibility: we're committed to making EMF as accessible as we can. If you have any requirements or requests you would like to discuss with us please feel free to email us on team@emfcamp.org. We'd also like to note that we offer free tickets for carers."

**Comment by SamLR** [comment]
I think this is closed by f488a4c
