### ISSUE TITLE
Replace incrementing Ids with GUIDs

### ISSUE THREAD

**Issue by SamLR** [emfcamp/Website#319]
Mostly to make it less easy to glean ticket information from valid URLs etc.

**Comment by marksteward** [comment]
We actually already have something suitable, in the form of the receipt/qrcode. We just need to allocate it up-front, which means filtering out bad words.

**Comment by marksteward** [comment]
If we do this, it should limited to URLs only, and supplement IDs, not replace them. We still need to pull out of the DB in a stable order in order to avoid deadlocks, and UUIDs don't provide stable ordering.

Places we might want to do this: User.id, Payment.id, Ticket.id, Proposal.id

**Comment by russss** [comment]
Relying on stable ordering to avoid deadlocks seems messy to me. This is where `SELECT FOR UPDATE` should be used really. At any rate, If we're not explicitly issuing `ORDER BY` - which I'm pretty sure we're not - then we're (accidentally) relying on the database ordering anyway, not the primary key ordering.

But I'm also not convinced there's a compelling case to move to UUIDs.

**Comment by russss** [comment]
I'm going to close this - I don't think the benefits outweigh the annoyances at this point (and if they do at any point, we should deploy these IDs for specific items rather than globally).
