### ISSUE TITLE
Cookies are apparently required for CSRF

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#323]
While obviously you can't log in without cookies, this also means you can't sign up to the mailing list without cookies, or submit a CfP you've just written. We don't provide a warning in advance.

If cookies are missing, we return this, which isn't helpful:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>CSRF token missing or incorrect.</p>
```

(we also return this when the referer header is missing, in case anyone finds this ticket by searching)

**Comment by marksteward** [comment]
Apparently we actually return:

```
Bad Request
Referrer checking failed - no Referrer.
```

when the referer header is missing. This shouldn't be necessary.

**Comment by russss** [comment]
We're now sending `SameSite=Lax` with our cookies, which is [widely supported](https://caniuse.com/#feat=same-site-cookie-attribute) I'm pretty sure this means we can just nuke all the CSRF protection now? Yay?

**Comment by marksteward** [comment]
I think we can nuke CSRF is the Origin header is set to the correct domain (and maybe also if Sec-Fetch-Site: same-origin is set).

**Comment by marksteward** [comment]
Done by dc53eef
