### ISSUE TITLE
Users should be able to transition a submission to the 'locked' state from 'edit'

### ISSUE THREAD

**Issue by SamLR** [emfcamp/Website#345]
Currently if an admin marks a submission for editing then the proposal will become locked after two days. Instead the proposal should remain in the 'edit' state until such a time as the user has made any required edits and moves it to the 'locked' state to be checked and anonymised.

The admin should receive a message that this has happened.

**Comment by marksteward** [comment]
Locked is pretty useless. We should probably just strip it out entirely.
