### ISSUE TITLE
Make our contact details a easier to find

### ISSUE THREAD

**Issue by SamLR** [emfcamp/Website#368]
Currently the only link is the company name in the footer.

Out contact details should probably include email addresses for e.g. sponsorship, content and volunteers

**Comment by marksteward** [comment]
It already does - https://wiki.emfcamp.org/wiki/Contact. We don't want to cover the site in email addresses

**Comment by marksteward** [comment]
Also, the sponsorship page includes our sponsor email address, and tickets the tickets address.

**Comment by marksteward** [comment]
I've fixed the CfP guidance email address.

**Comment by SamLR** [comment]
I'm not really sure having a page on the wiki really counts. It wouldn't need to be much but even a footer link to the about/company page (labeled as 'contact') would at least give people something they can find. Which they can't currently.

**Comment by SamLR** [comment]
I'm re-opening this. We're getting vendor requests via the cfp
