### ISSUE TITLE
Ability to issue complementary tickets

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#373]
These are needed for sponsors, journos, etc, and we should have all these in the main ticketing system instead of having a separate guestlist.

We need a new ticket type for this, as using an existing paid ticket-type will throw off the accounting. We can use a ticket-type with a discount token.

We need an admin form which, for a given ticket-type (which *must* have a zero price for the above reason) will:

* Accept a name, email, and number of tickets and then:
* Create the user account if not exists
* Create the new tickets and mark them paid
* Email the user with login details (this probably needs to be different email copy from the usual)

**Comment by SamLR** [comment]
I think this is closed by 159fc4b
