### ISSUE TITLE
Add form to capture proposal information for scheduling

### ISSUE THREAD

**Issue by SamLR** [emfcamp/Website#377]
Once a talk or workshop has been accepted there are several further bits of information that we'd like to capture:

- [x] Are there any further contributors to credit
- [x] Confirm that the proposer is happy with title/description
- [x] When does the proposer expect to arrive/depart
- [x] Telephone number
- [x] Available day/time check boxes
- [x] Are they happy for their <thing> to be filmed?
- [x] Any other special requests
- [x] Do they require a laptop to be provided for slides?

**Comment by timrterrible** [comment]
* Do they have any stage tech requirements beyond:

###### Audio
- x3 radio microphones (headset or handheld) [stages only]
- x1 wired handheld microphone [workshops only]
- x1 stereo feed from a laptop or similar 3.5mm audio source
- x2 13a sockets

###### Video
- x1 vga/hdmi/dvi/dp/minidp output for slide capture
- x1 preset camera angle for streaming [stages only]

**Comment by dominicgs** [comment]
I would change "Are there any further contributors to credit" to "are there any additional presenters?"

I would also change "When does the proposer expect to arrive/depart" to "are there any times when the presenter cannot speak?" as the constraints may not be at the start or end of the weekend.

**Comment by Jonty** [comment]
I would like to know when they expect to be arriving/departing as well as "times when they may not be able to speak", if possible.

Also:
* I would rather not ask when people would like to be scheduled, give me constraints not preferences
* Do they require a laptop to be provided for slides (ask this explicitly)

Further thinking in progress.

**Comment by marksteward** [comment]
I think we can merge #317 in here too.
