### ISSUE TITLE
Add IRC notifications to CfP

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#386]
Cuz IRC is the future.

Basically a simple webhook system that queues up events and resends them until they're confirmed.

**Comment by SamLR** [comment]
cf. https://github.com/emfcamp/Website/blob/main/docker/startup-irc-notify.sh

**Comment by SamLR** [comment]
Intended use case is general alerts such as "new message" or "new submission requesting help".

Given these will be published in #emfcamp-content they can't contain any identifying information but should e.g. link to the message

**Comment by SamLR** [comment]
closed by #1090
