### ISSUE TITLE
Per talk speaker ticket codes

### ISSUE THREAD

**Issue by dominicgs** [emfcamp/Website#419]
We would like to be able to generate ticket links on a per submission basis, perhaps tied to the submission email address.

We have a couple of people this year with speaker tickets and no registered talk.  It's fairly likely that they are part of a multi person workshop, installation or talk, but it's almost impossible to tell.

**Comment by dominicgs** [comment]
This is certainly for discussion post-2016.

**Comment by russss** [comment]
I would consider this a duplicate of #409, at least in the initial case.
