### ISSUE TITLE
Payment baskets

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#430]
When completing the first stage of the checkout process, items should be added to a basket.
Items in a basket are reserved for a finite amount of time, and are removed from sale.
Users can retain the contents of their baskets when changing payment methods.

**Comment by russss** [comment]
I think we can call this one broadly fixed, @SamLR?

**Comment by SamLR** [comment]
I think so. We should stress the system a bit just to check that it works as expected but I think getting some folks on staging is probably the best way to do that
