### ISSUE TITLE
New ticket model

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#431]
We want to change the ticket model to make site capacity planning easier and improve behaviour when tickets are selling out. Namely:
- The site has a **capacity**. This is fixed during planning and can be set (as it is currently) in config.
- This capacity is divided into **allocations**, such as "general admission", "sponsors", "vendors", etc. Allocations have an admin-defined capacity, configurable on the admin interface.
- The sum of allocation capacity cannot exceed the site capacity (but in practice may be lower to allow for headroom). 
- Each allocation is divided into **ticket types**. Ticket types do not have a capacity limit or an expiry date. Ticket types should have a unique name, and this name is what should appear on the customer's ticket.
- Each ticket type has one or more **price tiers**. These price tiers have a capacity limit and an expiry date, with the ticket type being priced at the cheapest available tier.
- Ticket types are removed from sale when either:
  - There are no active price tiers for that ticket, or
  - The total number of tickets in the allocation reaches the allocation capacity limit.
- Once a price tier's capacity limit is reached, it is not returned to sale without admin intervention.
- Once an allocation's capacity limit is reached, it is not returned to sale without admin intervention.
- A **ticket view** defines which ticket types will be displayed on a specific sales page.

Things we still need to contemplate:
- How do we deal with parking/campervan tickets? We could define that the site has multiple "capacities" and an allocation could be against one of those, but that may be over-thinking it. It may be easiest to just have a flag which says "this allocation is for admission tickets", and only those allocations are checked against site capacity.
- Do we try and shoehorn t-shirts, village tents, power cables, and other miscellanea into this model, or somehow break them out?

**Comment by marksteward** [comment]
We won't be selling parking/campervan tickets at multiple tiers simultaneously, so capacity for them can go in the active price tier.

The second question is a thorny, as I can't think of a way to make it particularly clean.

If we break t-shirts, tent, etc out we still need to do a lot of the same work with them - attaching them to payments, emailing out summary information, part-refunding. Most of this commonality is on the accounting, rather than event management side.

We could consider ticket type a subclass of **product**/stock unit/selection/insert better term here, and **tickets** a subclass of generic **purchases**/items. This separation is basically just to make it easy to use "Your ticket" instead of "Your order".

Assuming ticket types in this proposal are things like "Full Ticket", "U-16 Ticket" or "U-5 Ticket", only the first two would come under the "general admission" allocation, so allocations must be optional. We also have an overall limit for t-shirts, but want users to pick the appropriate size - should this be an **allocation** too, or a separate allocation-like table for non-ticket items?

I think we're looking at something like:

```
+-------------+    +------------+
|             |    |            |
|  Capacity   |    | Allocation |
|             |    |            |
+------+------+    +-----+------+
       |                 |
+------v------+    +-----v------+
|             |    |            |
| Ticket type <====|  Vendible  |
|             |    |            |
+------+------+    +-----+------+
       |                 |
+------v------+    +-----v------+
|             |    |            |
|   Ticket    |====|    Item    |
|             |    |            |
+-------------+    +------------+
```

**Comment by russss** [comment]
U5 tickets will still come under "general admission" as they still count against the site capacity.

I think T-shirt sizes, etc, are probably best done as a kind of "variant" rather than as individual ticket types (e.g., ideally the t-shirt should be one item with a size dropdown), which is yet another piece in the data model. I don't think we have to deal with capacity limits per-size as this is really only for t-shirts.

I'd say make allocations optional. Rename ticket type to "product" or something. And limit the stock number for non-tickets in the price tier (which there will only be one of).

**Comment by marksteward** [comment]
Another thing that this affects is discount/restricted tickets. We need to be able to offer discounts on individual ticket types, but also to allow someone to buy those and other tickets out of a vendor/speaker/verpeiler allocation. Will it be enough for a discount token to have an associated allocation, as well as a set of price tiers?

**Comment by marksteward** [comment]
We need to also add day tickets, and account for them in the capacity somehow. Can we necessarily assume people have left site a day after they've arrived?

**Comment by russss** [comment]
The ticketing system doesn't need to be concerned with day ticket holders overstaying their welcome. That's an operational issue.

**Comment by marksteward** [comment]
The main problem here is not including price tiers under ticket type. Check again.

**Comment by russss** [comment]
Refunds of tickets shouldn't reactivate expired price tiers.

**Comment by marksteward** [comment]
And while we might sell t-shirts alongside tickets, that can be done in python, not the data model,

**Comment by marksteward** [comment]
Here's a suggestion based on IRC chat:

```
+---------------+    +---------------+
|               |    |               |
|   Capacity    |    | ProductGroup  |
|   (config)    |    | CapacityMixin |
+-------+-------+    +-------+-------+
        |                    |
+-------v-------+    +-------v-------+
|               |    |               |
|  TicketType   <====|    Product    |
|               |    | CapacityMixin |
+---------------+    +-------+-------+
|               |            |
| issue_badge   |    +-------v-------+
| transferrable |    |               |
|               |    |   PriceTier   |
+-------+-------+    | CapacityMixin |
        |            +-------+-------+
        |                    |
  +-----v-----+       +------v------+    +----------+
  |           |       |             |    |          |
  |  Ticket   <=======|  Purchase   |====>   Item   |
  |           |       |             |    |          |
  +-----------+       +-------------+    +----------+
```

**Comment by marksteward** [comment]
For now, we're doing this:

```
                                                  +----------+
                                                  |          |
                         ...........      +-------v-------+  |
                         .         .      |               |  |
         .................  Type   <......| ProductGroup  +--+
         .               .         .      | CapacityMixin |
         .               .....^.....      +-------+-------+
         .                    .                   |
         .                    .           +-------v-------+   +---------------+
         .                    .           |               |   |               |
         .                    .           |    Product    <---+  ProductView  |
         .                    .           | CapacityMixin |   |               |
         .                    .           +-------+-------+   +---------------+
         .                    .                   |
         .                    .           +-------v-------+
         .                    .           |               |
         .                    .           |   PriceTier   |
         .                    .           | CapacityMixin |
         .                    .           +-------+-------+
         .                    .                   |
         .                    .           +-------v-------+
         .                    .           |               |
         .                    .           |     Price     |
         .                    .           |   read-only   |
         .                    .           +---------------+
         .                    .                   |
+-----------------+     +-----------+      +------v------+
|                 |     |           |      |             |
| AdmissionTicket <=====|  Ticket   <======|  Purchase   |
|                 |     |           |      |             |
+-----------------+     +-----------+      +-------------+
```

I might get rid of the Ticket/AdmissionTicket bit, but for now that holds admission-specific data like checked_in and badged_up, and makes it easy to filter for only ticket purchases in the DB.
