### ISSUE TITLE
Allow users to create an account somehow

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#438]
For volunteers and favouriting things from the schedule. Only enable it shortly before the event, to encourage people to transfer tickets.

**Comment by davidc** [comment]
partly done (with USER_SIGNUPS feature flag), but a question before I send a pull request: do you want it to also automatically log them in or just automatically send them a login link?

**Comment by marksteward** [comment]
Log them in, I think. Once you have an account, you can always request a login link, so there's no point making them do the little dance.

**Comment by marksteward** [comment]
Thinking more, it's probably a bad idea to create an account with nothing associated. We should do the login dance, same as when admins create an account.

**Comment by marksteward** [comment]
I think for now I'm also going to require a time-limited token from an admin, to prevent random spam.

**Comment by marksteward** [comment]
Closed by #636
