### ISSUE TITLE
Streaming opt-outs?

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#444]
If we have any, they need to be exposed in the frab feed so the c3voc code knows not to record them.

@Jonty?

**Comment by Jonty** [comment]
We have a number of people who have opted out (15 at last count).

**Comment by russss** [comment]
Ah yes, this is Proposal.may_record, which needs to be exposed in the Frab feed.

**Comment by marksteward** [comment]
Fixed by d16aea8
