### ISSUE TITLE
Schedule viewer event boxes are misaligned

### ISSUE THREAD

**Issue by Jonty** [emfcamp/Website#448]
1:44PM The boxes are misaligned on the schedule. Look at Sex Robots: https://www.emfcamp.org/schedule
1:44 PM It should start on the line just below the top, and end exactly at 8pm
1:44 PM Everything is offset by 1px per hour
1:46 PM If I change hour_size_px back to 132 it fixes it, but then the hour period on the left slips

**Comment by Jonty** [comment]
I think we need to be looking at this: http://docs.dhtmlx.com/scheduler/samples/02_customization/09_timestep.html

But I can't get it to work!

**Comment by marksteward** [comment]
Maybe fixed with 20f71cf
