### ISSUE TITLE
Red "now" line on schedule disappears when scrolling horizontally

### ISSUE THREAD

**Issue by ultrafez** [emfcamp/Website#452]
When viewing the schedule, the horizontal line that indicates what time it is disappears when using the blue "<" and ">" buttons to scroll the view horizontally. The line reappears when resizing the window, however.

Expected behaviour: red line stays visible when scrolling

**Comment by ultrafez** [comment]
Never mind, I see it's an issue in the DHTMLX Scheduler library

**Comment by marksteward** [comment]
Yep, sorry. We'll do our best to fix it if we get time.
