### ISSUE TITLE
Schedule popup text unusable on mobile phones

### ISSUE THREAD

**Issue by nomis** [emfcamp/Website#460]
Using Chrome on a Nexus 5, the popup text for an event is unusable because the space allocated to the scrolling text was usually less than half a line (depending on the length of the event title) requiring very awkward scrolling to read it.

**Comment by Jonty** [comment]
We're really sorry about this - we just didn't have time to fix it once the event got into full swing!

**Comment by marksteward** [comment]
See also #457

**Comment by SamLR** [comment]
Closing as duplicate of #457
