### ISSUE TITLE
Feature request - Add links to recordings/streams in lineup and description pages

### ISSUE THREAD

**Issue by kliment** [emfcamp/Website#461]
Since many talks were recorded this year, but the ccc media page shows them in a counterintuitive order and contains nothing but the titles, the lineup and description pages on the EMF site are a much better way to discover talks for people who missed them or were unable to attend. I feel it would make sense to add links to the recordings on the lineup page and the individual event description pages.

**Comment by SamLR** [comment]
I believe this is fixed by 63bb2bbd2 and similar
