### ISSUE TITLE
Ticket flow: opt-in checkbox for emails about future events

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#468]
Be explicit about email volume and ease of unsubscription. Possibly default it to checked.

**Comment by marksteward** [comment]
I think it should default to checked, it's quite easy to miss at the moment. Or maybe a radio box/toggle buttons?

**Comment by russss** [comment]
GDPR guidance says pre-ticked boxes aren't consent, so it needs to default to unchecked.

**Comment by marksteward** [comment]
OK, I'll make it more clearly part of the form flow.

**Comment by russss** [comment]
This is now added, it requires some general styling tweaks which I'll do separately
