### ISSUE TITLE
Upgrade to new GoCardless library

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#535]
The old GoCardless API, and along with it the `gocardless` python package, is being shut down on October 31st, so we'll need to upgrade to the new one (`gocardless_pro`) before we start selling tickets.

* [Overview of changes](https://support.gocardless.com/hc/en-us/articles/115000436689-Overview-of-changes)
* [API Reference](https://developer.gocardless.com/api-reference/)

**Comment by marksteward** [comment]
Done, but see #575
