### ISSUE TITLE
Reconsider user_limit

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#581]
It's hard to optimise away the N+1 here, as we need to check the number of purchases the user has made. We also currently checking on the PriceTier level, which means a user can easily circumvent the limit by buying in different rounds (although they can also do this by creating a separate account).

I think we should at least remove the check on previous purchases. It's cute to show it dropping but not necessary.

**Comment by russss** [comment]
I'm not concerned about this, scrap it. We can always check it offline.
