### ISSUE TITLE
Fix purchasing free tickets only

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#591]
Somehow we've broken the ability to buy free tickets (e.g. Under-5). They should require the user to have/be buying a full ticket but not necessarily a corresponding payment.

**Comment by SamLR** [comment]
To confirm the check we're applying for this is effectively `if len(user.owned_products) > 0`?

**Comment by marksteward** [comment]
Yeah, almost. The missing case is where the user already has admissions tickets and is only buying free ones, so if we check they've got a ticket in the admissions product group, and that ticket isn't reserved or cancelled, they should be able to set those free tickets straight to paid.

**Comment by SamLR** [comment]
How is that not covered by `owned_tickets`, which should include any tickets they've bought for themselves (and not transferred) as well as tickets transferred to them. Or do you want it to be more specific, i.e. check that at least one `owned_ticket` is an std adult admission ticket?

**Comment by marksteward** [comment]
owned_tickets includes reserved ones, so would include the free ticket the user's trying to buy

**Comment by marksteward** [comment]
Ugh, I didn't read this carefully enough. I used owned_tickets, which means a user can buy free tickets and no others. Will fix tomorrow, along with a redirect back to choose_tickets from the payment page.
