### ISSUE TITLE
Sort out lock contention when buying tickets

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#599]
We were seeing successful requests take 15 seconds and failed ones even longer:

```
Mark@gauss:~/Website$ sudo grep 'POST\ /tickets ' /var/log/nginx/access.log|sort -t'    ' -k7 -n|cut -d'        ' -f3-7|tail
29/Jan/2018:19:00:48 +0000      POST /tickets HTTP/1.1  500     5032    13.231
29/Jan/2018:19:00:38 +0000      POST /tickets HTTP/1.1  302     241     13.363
29/Jan/2018:19:00:46 +0000      POST /tickets HTTP/1.1  200     16044   13.823
29/Jan/2018:19:00:31 +0000      POST /tickets HTTP/1.1  302     241     13.978
29/Jan/2018:19:00:41 +0000      POST /tickets HTTP/1.1  500     5032    14.347
29/Jan/2018:19:00:44 +0000      POST /tickets HTTP/1.1  200     11423   14.520
29/Jan/2018:19:00:38 +0000      POST /tickets HTTP/1.1  302     241     14.821
29/Jan/2018:19:00:35 +0000      POST /tickets HTTP/1.1  302     241     14.871
29/Jan/2018:19:00:49 +0000      POST /tickets HTTP/1.1  200     11870   16.062
29/Jan/2018:19:00:43 +0000      POST /tickets HTTP/1.1  500     5479    17.535
```

This is no good. We should run this in one query, not multiple.

**Comment by russss** [comment]
This is a bit difficult to identify without more metrics - I'm not sure what you mean by "one query, not multiple".

My reckon is that this is purely due to CPU contention, which slows the lock-holding process down. (Which is basically priority inversion I guess.)

I'm not *too* disappointed by this performance to be honest - there were ~300 people trying to buy tickets simultaneously. This is only going to be an issue on smaller batches anyway.

We might be able to improve things just by reducing the concurrency. I'd rather not over-optimise this stuff when we don't really need to.

**Comment by marksteward** [comment]
I think it's more that this code needs to go back-and-forth between the DB and the python workers quite a bit. Someone buying a full ticket and parking will do something like this:

- first flush
  - lock & update product_group, product_group, product, price_tier
  - get product_group, product_group
  - insert purchase
- get price, price_tier, product, product_group, product_group
- second flush
  - lock & update product_group, product, price_tier
  - insert purchase
- commit

On my VPS with nothing else running, this takes 130ms. Moving locking to the end will reduce that to ~13ms, and doing admissions tickets last will halve the period of that which requires a lock on the admissions product_group.

**Comment by marksteward** [comment]
If I can work out how to force sqla's update ordering, this will just be a matter of removing the flush.

**Comment by marksteward** [comment]
I've added some working in the comment for __add_event_listeners. The relevant bit here is :

> SQLAlchemy locks from parent classes down. This is slightly suboptimal, but not worth working around. It appears to update in PK order within a class, so self-referencing classes shouldn't deadlock.

The process currently looks like this:
- flush any new purchases (there may not be any) to insert them in the DB and get them reloaded
- full flush, which locks rows from the top of the hierarchy down
- check the resulting capacity values after that flush
- commit, freeing the locks
