### ISSUE TITLE
Log IP address or session identifier

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#600]
We used to have something like this I thought. Where's it gone?

It was #165 - we should also add a request identifier or log the start of each request.

**Comment by russss** [comment]
Well, that got lost in my logging changes but looking at e1e3422 it would have been erroneous anyway - since we use eventlet gunicorn workers there can be multiple requests processed within each process.

**Comment by russss** [comment]
Fixed in 01abb91
