### ISSUE TITLE
Don't let people buy parking/campervan tickets if they don't have an admission ticket

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#631]
People should not be able to buy parking/campervan tickets unless they already have an admission ticket, either in their basket or already purchased.

**Comment by russss** [comment]
I think we can generalise this as "you shouldn't be able to buy a parking/campervan ticket without an admission ticket".

**Comment by marksteward** [comment]
More than this, I think you shouldn't be able to reserve them, as we got a bunch of people stuck in limbo with a reserved parking ticket in the latest round.

**Comment by russss** [comment]
This is quite similar to #591.

**Comment by russss** [comment]
This hit a lot of people in 2020 so it's essential for 2022.

**Comment by SamLR** [comment]
Was thinking we should set things up so that people can make their accounts before tickets go on sale and create a basket of what they want so that folks don't have to race with the form

**Comment by russss** [comment]
Regardless of what else we do, we will want to implement this ticket anyway as an additional check.

**Comment by kliment** [comment]
One thing to note is we need to make sure this does not affect people who did not buy a ticket themselves but had one transferred to them.

**Comment by davidc** [comment]
Can we split these "extras" onto a separate page/step entirely? So the first page, all you have to do is choose your tickets, click, and they're reserved. Then you can choose parking and so forth with less rush.

**Comment by russss** [comment]
Yes, we may also do that, but that is also not in scope for this ticket.
