### ISSUE TITLE
Validate email addresses on account creation

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#654]
Just a superficial check that it looks like an email address would help.

**Comment by marksteward** [comment]
We already do this by using the Email() field type

**Comment by russss** [comment]
We may be missing that somewhere then, as the reason I filed this ticket was because I had to fix an email address which was clearly wrong, although I can't remember exactly how.

**Comment by marksteward** [comment]
Maybe in mailchimp?

**Comment by russss** [comment]
No, it was definitely in our database.

**Comment by marksteward** [comment]
The only one I can find (where User doesn't match the latest UserVersion) is an `@gmai.com`. That's hard to catch.

**Comment by Jonty** [comment]
This was a user created by filling in the CFP, where it was two people submitting and trying to be clever so the email address was "foo@bar.com; cheese@yum.org"

**Comment by marksteward** [comment]
OK, confirmed that that passes the Email() validator. b26b10d should stop most cases in the client.

**Comment by marksteward** [comment]
Will be fixed by https://github.com/wtforms/wtforms/commit/2a24d30, which will be in WTForms 2.2 (hopefully soon?)
