### ISSUE TITLE
Add ticket sales page for speaker tickets

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#655]
We need a page which allows speakers to buy a weekend ticket, day ticket, and a +1 ticket for a friend.

It would be nice to do this automatically if possible - we could have a ticket attribute which is "only purchasable by people with accepted CfP entries" to do this, and then limit the amount to 1 using the personal limit (assuming it still works).

If we do this we could then automatically link this sales view for people who have approved submissions.

Need to make sure that we're not over-selling these though...

**Comment by marksteward** [comment]
I've stored the attribute on ProductView. This means we don't need to store anything new on the ticket, it just comes from a new carve-out with `"is_transferrable": false`.

**Comment by marksteward** [comment]
Fixed with 1e61473. It'd be nice to also let speakers pick supporter/gold supporter tickets (per #140/#169) but that's not currently compatible with `personal_limit`.
