### ISSUE TITLE
More documentation for new developers

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#67]
Make it easier for people to get up to speed.  To add to the wiki (in order of priority):
- Overview of ticketing system
- Getting started (README.md) and differences from live
- Flask cheatsheet
- Minimal Git workflow
- SQLAlchemy guide and "just get it working - text()"
- WTForms

Do we need to tidy/comment/refactor code to make it easier to contribute?  What's people's main concern about making changes?

**Comment by russss** [comment]
I'm going to close this as it's super open-ended. We have got a bit better at this.
