### ISSUE TITLE
Proposal topics/tags

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#678]
We want to assign topics to each proposal, for monitoring purposes and maybe use in the schedule? These will not be used/visible in the review interface.

There will be a fixed list of topics, and multiple topics can be applied to the same proposal by admins.

**Comment by Jonty** [comment]
Additionally:

* We need to be able to filter proposals by tag/state
* We need a view which shows (by state) the tags by %

It would be nice to pre-define the approved tags up-front to ensure we don't end up with deviation.

Stretch goals:
* Setting % goals on a per-tag basis, and showing which tags are over/under those percentages on the monitoring interface

**Comment by SamLR** [comment]
closed by #1295
