### ISSUE TITLE
Proposal edit page should allow converting to any other type of proposal

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#679]
At the moment we have a couple of hard-coded "convert to performance"/"convert to workshop" buttons. We should allow proposals to be converted to any other type.

There's a few interesting bits here involving required fields...

**Comment by marksteward** [comment]
The only additional fields are `attendees` when converting to a workshop, and `size` when converting to installation. They're not required by the schema, and I think it's OK to leave until the next update to add them.

**Comment by marksteward** [comment]
This was done with 8283b86. I've added #717 for the "interesting bits".
