### ISSUE TITLE
Make it possible for people to sign up to the mailing list at any point

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#696]
It's not currently possible to sign up to the mailing list while the site is in the "ticket sales" state.

This is partly an intentional decision because we don't want to put people in a situation where they sign up to the mailing list expecting to get notified about subsequent ticket (re-)sales, but then don't receive any emails because we don't send them for every single ticket release.

**Comment by russss** [comment]
The reason we don't have the mailing list signup on the front page at the moment is because we don't want people assuming they'll get reminders about ticket re-sales etc for this year. 

Some of this is cost-motivated due to mailchimp but I don't like the expectation that it provides.

**Comment by russss** [comment]
To be clear "at any point" here means that there isn't a way of signing up to the mailing list when ticket sales are active.

**Comment by marksteward** [comment]
This is now on https://www.emfcamp.org/about/contact
