### ISSUE TITLE
Limit word length of CfP description to a sensible length

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#738]
It would also be good to somehow discourage people from putting info for reviewers/content team in the description field.

**Comment by dominicgs** [comment]
We could split the box in two:
 * Description - the thing that appears on the site
 * Additional information - anything else we need to know

**Comment by russss** [comment]
We already do that, but some people apparently didn't get the hint in 2018. Word limit should help with that hopefully but we could also improve the wording.

**Comment by dominicgs** [comment]
Sorry, I was unclear.  I agree on the length limit, I also think the labels could do with changing.  Right now the second box is called "requirements" and everybody seemed to use it for equipment requirements.
