### ISSUE TITLE
Improve training UI

### ISSUE THREAD

**Issue by SamLR** [emfcamp/Website#764]
The "train users" view should have some basic filtering to make it easier to find users

**Comment by idnorton** [comment]
Train users UI is at https://www.emfcamp-test.org/volunteer/train-users and looks like:

![image](https://user-images.githubusercontent.com/1237947/123683819-9559d400-d844-11eb-8305-66e7381f3395.png)

And then on selecting a role:

![image](https://user-images.githubusercontent.com/1237947/123683929-b8848380-d844-11eb-928d-78f302a85d81.png)

**Comment by idnorton** [comment]
Permissions to be able to see the training and train people?
Do we need to be able to delegate the permissions to team leads or trainers who can only see their own training?

**Comment by idnorton** [comment]
Original user story https://github.com/emfcamp/software_stories/blob/master/volunteer_system_user_stories.md listed multiple roles:

* Trainer
* Manager

Not sure if these were implemented or if this access can only be granted by site admins?

**Comment by idnorton** [comment]
We need some way to manually set people as trained from the admin UI.

This can currently be achieved via the role UI:
![image](https://user-images.githubusercontent.com/1237947/128750378-60f7ca3a-adb4-4c43-b57d-88a662fb6da2.png)

It would be good to be able to see trained roles within a volunteer record:
![image](https://user-images.githubusercontent.com/1237947/128750466-85b36f69-25fd-4c6c-ae28-e7d828f67213.png)

**Comment by ormiret** [comment]
Currently think bar will be the only role that requires training and marking as trained is automatic after they do it so don't think this UI will be needed, so closing for now.
