### ISSUE TITLE
Event Schedule import

### ISSUE THREAD

**Issue by SamLR** [emfcamp/Website#767]
Ideally shifts for stages should be aligned with the talks/events occuring inside of them (1event = 1 shift) this will need a separate import and to replace the existing hard-coded list

**Comment by idnorton** [comment]
There's some discussion been had about if these should align in all cases or not. The issue perceived by the volunteer team is that as schedules drift, people still want to know when their volunteer slot is going to be and when they'll be done to make plans outside of their volunteering activities.

We've discussed the idea of making the volunteer slots fixed for day long schedules like talks but with some concept of flexibility with regards to non specific events that make it clear to people that the time isn't fixed and is free to float.

Needs more discussion with the team leads to see if/how we see this potentially working and identifying which roles we couldn't make this work for.

**Comment by jellybob** [comment]
Discussion with stage, who would be the main users of this, resulted in the conclusion that something like this would result in far too much volunteer turnover. Closing.
