### ISSUE TITLE
Schedule overview should display speaker name

### ISSUE THREAD

**Issue by saerdnaer** [emfcamp/Website#792]
In my option the schedule overview should include the speaker name (maybe a lighter grey colour) after <del>or before</del> the title:
<img width="699" alt="image" src="https://user-images.githubusercontent.com/40266/44947902-15009380-ae0c-11e8-8ae9-f8872a044908.png">

**Comment by marksteward** [comment]
There's very little space, and we want to encourage people to look at the topic of the talk rather than the speaker, so after would be better I think.
