### ISSUE TITLE
Some sort of site wide messaging/information system

### ISSUE THREAD

**Issue by jellybob** [emfcamp/Website#793]
To communicate things that we're currently only really doing over IRC/Twitter - schedule changes, t-shirt sales, badge availability etc. Ideally it would be hooked into displays in key areas around the site, the inter-session stage displays, and as a stretch goal support pushing messages to badges and/or SMS.

**Comment by SamLR** [comment]
This already exists in a very basic form (the admin/message system + now and next page).

As I understand it though the stage interstitials were done using event stream which VOC manage and messages were sent via the wiki.

Obviously a more widely accessible (both in terms of read & write) would be useful and has been planned for a while ;)
