### ISSUE TITLE
More "about the event" content

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#798]
We should move some of the essential info about the event from the wiki to the main site so it's more visible, easy to read, and persists between events. Including:

* Facilities on site (toilets/showers/vendors/etc)
* Info about tickets (when they're issued, transferring them, whether you need to print them out, etc)
* When you can arrive/leave, when things start, etc.
* Accessibility
* FAQ? Or perhaps get rid of the FAQ in favour of info pages.

**Comment by vetraskr** [comment]
- Vendor information page with requirements and expectations, times etc. (Can probably be lifted from the contract.)
- More visible contact information for conduct? ie, a big button & form to quickly report concerns, and nice copy about who the information is visible to?

**Comment by jellybob** [comment]
I have a strong preference for killing off the FAQ and replacing it with some more structured information pages. I'm also quite happy to work on those as there's quite a bit of stuff already written up for people working on the info desk that should be reasonably easy to port over.

**Comment by SamLR** [comment]
I think there's something to be said for keeping a FAQ on the wiki as a staging post point for questions but there's a lot of it that should be codified on the main site.

**Comment by Jonty** [comment]
I think we should aim for what @jellybob proposes, but I suspect we'll need a dumping ground for assorted questions/answers for a long time (which is basically the FAQ). It would be good to move things out of it though.

**Comment by russss** [comment]
I've done the structure for this and added a few pages to the [about section](https://www.emfcamp.org/about). It needs more content writing, but I've removed it from the ticket pre-sales milestone.
