### ISSUE TITLE
Archive 2018 data and clear DB

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#807]

**Comment by marksteward** [comment]
#538 will need updating for this year

**Comment by russss** [comment]
@marksteward @Jonty I need your input on what new things we need to preserve this year. I don't want to keep the DB backup this time.

The one thing I can think of is volunteering (and speaker?) data and email addresses so we can use them to issue vouchers.

**Comment by Jonty** [comment]
Yes, both of those.

I'd also like to somehow keep a list of email addresses that submitted things we _didn't_ accept, so we can boost them if they submit again in future years or something - perhaps hashed? Unsure.

Would also like to keep info on who registered villages/things on the map so we can contact them about doing it again in the future. Probably just a mailing list to pop them onto.

**Comment by russss** [comment]
I've added exporting volunteer/speaker emails in #819.

> I'd also like to somehow keep a list of email addresses that submitted things we _didn't_ accept, so we can boost them if they submit again in future years or something - perhaps hashed? Unsure.

Is this even a good idea? I'm not sure why we'd want to boost people who previously submitted talks but weren't accepted (or indeed how we'd even do that).

> Would also like to keep info on who registered villages/things on the map so we can contact them about doing it again in the future. Probably just a mailing list to pop them onto.

I'm saving the names of villages, but not who they're associated with. I reckon if they want to do it again they'll do it again (plus we can probably get them off the wiki).

**Comment by russss** [comment]
OK, in the interests of getting new dev moving I'm going to take a DB backup, this will live in the usual location (the emfcamp.private Keybase folder) only, then go ahead run this export.

I will create a new issue for extracting any additional data from this DB.
