### ISSUE TITLE
Responsive and easier to use schedule 

### ISSUE THREAD

**Issue by Pezmc** [emfcamp/Website#811]
Requirements so far (WIP):

 - Easy staring and filtering of the schedule
 - What's on now/next
 - Easy to use on mobile (PWA)
 - What events that I want to see clash

Other ideas:
 - Search (tags/people/stages)
 - "Make your own schedule" (starring)
- What events I've starred are on now/next

@jellybob said he had some design ideas and was going to sketch some things out, @Jonty said he'd find time soon to write out a list of user stories/use cases.

Possible Inspiration:
 - https://sched.com/
 - https://clashfinder.com
 - http://www.displayweek.org/2019/Program.aspx

Mockup (from @jellybob):

![image](https://user-images.githubusercontent.com/507155/61221702-f1d38f80-a710-11e9-8f53-c7dc392fb1f2.png)

**Comment by jellybob** [comment]
By some miracle my branch for this wasn't too painful to merge this year's changes in to so I'm going to resurrect it and see if I can get it to a point where its usable by real people.
