### ISSUE TITLE
Ticket Sales Voucher System

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#815]
We need to allow people to buy tickets using vouchers. We will be issuing vouchers to volunteers to allow them to buy tickets outside of the public sale.

This is a sketch design document for vouchers - suggestions are welcome.

## Overall Design

Unlike the CCC system, we should ensure that *all vouchers guarantee the holder a ticket until their expiry date*. This means that the capacity logic needs to change to take unredeemed vouchers into account.

(Some?) vouchers should also give the holder an opportunity to buy friends/family tickets - perhaps one additional adult ticket and a number of U18/U12 tickets.

It's possible we might also want to issue a single voucher code for a group of people to buy tickets, so perhaps the number of adult tickets the voucher issues should be configurable.

## Implementation Thoughts

It's probably worth having a "voucher class" entity, which each voucher is a member of, to set the parameters of the voucher. The voucher class should be linked to the ProductGroup which the voucher will issue tickets from.

**Comment by SamLR** [comment]
Not specific to the implementation but I know Alia would like to have an allocation of ticket vouchers to pass on as part of diversity out reach
Also we should check how this intersects with vouchers for sponsored tickets to support sponsored tickets.

**Comment by russss** [comment]
Diversity vouchers should definitely be a consideration in this design.

Vouchers for sponsors might work well too, as we could give them a single voucher code which they can redeem themselves, rather than the current approach of asking them to send everyone's details to us.

**Comment by SamLR** [comment]
NB I meant "sponsored tickets" in terms of subsidised tickets for those less-able to pay
(although I guess it does also work with sponsor tickets)

**Comment by SamLR** [comment]
Just found we have more notes on this in #643
