### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#826]
Oddly, this repo doesn't have a license. It should. I propose we use AGPL3. Any objections?

Tagging in significant contributors:
@marksteward @SamLR @Jonty @JasperWallace @jellybob @davidc @vetraskr @marekventur

**Comment by SamLR** [comment]
fine by me (equally I have sod all knowledge of the differences between the licenses so *shrug*)

**Comment by davidc** [comment]
My contributions are limited so I leave this up to you!

**Comment by jellybob** [comment]
I have no strong feelings on this, go ahead

**Comment by marksteward** [comment]
I assumed we'd pick MIT but happy with AGPL too.
