### ISSUE TITLE
Make the presumption against Q&A clear during acceptance/finalisation

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#827]
From #812:

> In CFP, encourage people to do Q&A outside the tent: "Please note that in the event of timing overrun, you may not be able to have Q&A time as part of the presentation; please be prepared to take questions outside the tent after your talk is over."

I actually think we should go further, with something along the lines of: "We would strongly prefer you do not do a Q&A session after your talk - these are hard for us to manage and frequently unproductive. Please consider taking questions outside the tent or in the bar instead."

We should put this in the acceptance email and possibly also in any subsequent emails we send to speakers (but only for "talk" proposal types).

**Comment by Jonty** [comment]
Closing in favour of #1256
