### ISSUE TITLE
External URLs are generated with HTTP prefix

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#834]
In production, external URLs are being generated with http:// rather than https://. This is despite `PREFERRED_URL_SCHEME='https'` being set in the config. I don't know why.

**Comment by marksteward** [comment]
A quick fix is to modify main.external_url. This has happened before and can't remember why.

**Comment by russss** [comment]
Looks like flask uses the scheme of the request in preference to `PREFERRED_URL_SCHEME` so I reckon we're probably not sending the appropriate header from nginx.
