### ISSUE TITLE
Display EUR bank details as an EPC QR code

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#841]
https://en.wikipedia.org/wiki/EPC_QR_code

**Comment by will-h** [comment]
FYI, the template for generating these QR-codes in pretix is here:

https://github.com/pretix/pretix/blob/f0128429e42b995df6ab2377f20b123a4f866c10/src/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/pending.html#L39-L53

There is also a bank:// url code there we may wish to include.

**Comment by will-h** [comment]
Oh, yes, and PDF of spec is here https://www.europeanpaymentscouncil.eu/sites/default/files/kb/file/2018-05/EPC069-12%20v2.1%20Quick%20Response%20Code%20-%20Guidelines%20to%20Enable%20the%20Data%20Capture%20for%20the%20Initiation%20of%20a%20SCT.pdf

**Comment by jayaddison** [comment]
Some notes/findings - it looks like pretix uses https://github.com/jeromeetienne/jquery-qrcode (cf. https://github.com/pretix/pretix/blob/a43ee054ad183ee0e174972a25753fcbcd86fd52/src/pretix/static/pretixcontrol/js/jquery.qrcode.min.js) to render QR codes client-side.

There's also https://pypi.org/project/segno/ which is a pure-python QR generation library and supports EPC QR as of recently.

**Comment by russss** [comment]
My preference would be to move our existing QR code generation to using segno, and then use that for this too. It's a little fiddly to test that though (and ticket generation hasn't been tested since I switched deployment to docker).
