### ISSUE TITLE
Installation CfP Changes

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#853]
The installation CfP is disabled for the moment.

The reason for this is we need to be more selective about which installations "deserve" to go through the CfP, in light of the fact that accepted CfP entries are entitled to discounted tickets and vouchers for future events. I've spoken to people who think their project/installation needs to go through the CfP, when it really doesn't.

Installations only need to go through the CfP if:

1. They are asking for funding.
2. They're large, of complex construction, and/or require consideration in site planning, safety, or insurance.
3. They have significant power requirements.

We need to have a set of clear criteria for whether an installation needs to be submitted through the CfP, potentially with a set of questions people have to answer before it lets them submit.

We probably also need a new "rejected" state which means "this is fine but it doesn't need to go through the CfP".

**Comment by prehensile** [comment]
FWIW, the Shiny team (mostly Richard @jarkman) have been working out and writing up an 'Installation Support Service" which attempts to framework a lot of stuff around bringing / building things at EMF and asking for money.

https://docs.google.com/document/d/13FrU9dC8ha7lx644tTq7-WsCMVDXdZslYUgntrwl-Qs/edit?usp=sharing

It doesn't address directly whether things should go through the CfP or not; perhaps it should.

**Comment by prehensile** [comment]
Worth mentioning here because I think we’re attacking the same problem from slightly different directions. Also, we were hoping to publish this doc somewhere (the EMF website or 2020 wiki?) in sync with the CfP going out.

**Comment by Jonty** [comment]
@prehensile We'd like to get the CFP live ASAP (which is identical to previous years other than installations), so we're removing installation submission for now with messaging that the installations CFP will launch soon. Gives us a bit to get this hammered out.

**Comment by russss** [comment]
This has been done now.
