### ISSUE TITLE
Flag when we're about to accept multiple $things by the same person

### ISSUE THREAD

**Issue by Jonty** [emfcamp/Website#862]
We often have a problem where we will accept more than one talk/workshop/thing from the same person because they submit 20 and hope one will get through.

When the talks are ranked we accept all talks up to the judgement score, so this can include multiple $things by the same person.

We would really like to avoid emailing people saying multiple things have been accepted, however it's not a hard rule like "only one thing per person" as often people will give a talk and a workshop, or a talk and a performance.

We can either change the acceptance interface to flag up when we're about to accept more than one thing by the same person (remember things may already have been accepted in previous rounds), or we could change it to only accept one of each type of thing, or something.

Thoughts? /cc @SamLR

**Comment by SamLR** [comment]
I don't think it'll be too hard to add "other submissions by this user" to one of the admin pages/a tab and either add some sort of flag or alert symbol if it's greater than X

**Comment by SamLR** [comment]
@Jonty I'll add a check between the close_round and rank steps.

**Comment by Jonty** [comment]
@SamLR I think that sounds reasonable! What workflow do you imagine when that happens though?

**Comment by SamLR** [comment]
@Jonty still slightly unsure. I'm thinking that the first item of any category that gets accepted automatically declines any other submissions (and alerts us) sending an email along the lines of 

> you submission X has been accepted, we tend to only accept a single submission from each person so your other submissions Y, Z have been declined. We hope this is ok

Whatcha think?

**Comment by Jonty** [comment]
Something like that might work, yeah. I'd like to be able to override it, just in case there are ~other circumstances~. Maybe a checkbox?
