### ISSUE TITLE
Volunteer training UI / bar training

### ISSUE THREAD

**Issue by idnorton** [emfcamp/Website#867]
Primarily to handle the Bar training, the model and basic view for dealing with volunteer training has been added but we now need UI to handle a volunteer going through the process of completing training.

We have the following in the model:

* Training
* TrainingQuestion
* TrainingAnswer

For a given set of training, it can have one or more questions which can have one or more valid answer.

Depending on the requirements of the training, the test can automatically sign someone off based on a pass mark, or require someone to manually confirm training completed.

**Comment by idnorton** [comment]
So we discussed this issue on PR #884 and the consensus of opinion was that there was no requirement to have online editing of the training, questions and answers and it would be preferable to have those stored in a static JSON file in source control than data driven in the db.

Here's a first stab at a json data structure based on the 2018 training questions and answers.
[training.txt](https://github.com/emfcamp/Website/files/4247126/training.txt)

Comments and thoughts on this? It's basically a lift and shift of the data I manually entered into my local database instance and feels about right.

**Comment by idnorton** [comment]
Comments and feedback discussion happened on IRC and I forgot to add them here:
```
--- Day changed Wed Feb 26 2020
11:46 < idn> Any comments or thoughts on the suggested JSON format in https://github.com/emfcamp/Website/issues/867 peeps?
11:48 <@ms7821> I like it
11:51 < idn> Was contemplating one file per training thing, which is only bar at the moment but could be more later.
11:51 < idn> Then keeps things self contained.
11:52 <@ms7821> yeah that would be good
11:52 < idn> Also tagging the correct answer means that we could potentially have one or more valid answers with checkboxes rather than just a single choice drop down
11:52 <@ms7821> yep
11:53 < idn> Cool beans, I'll try and do something with that in the next week then
11:53 < idn> Thanks for the sanity check ms7821
11:53 < idn> (this is basically a lift and shift of the db model I did)
12:38 < jontyw> I like it too
12:39 < jontyw> And this comes from someone who has professionally studied basically all available survey tool export/import formats
12:39 < jontyw> :P
12:47 < idn> jontyw: Thanks :)
12:47 < ormiret> idn: one comment, the correct (and pass_auto) flags are strings in that, "false" is truthy
12:48 < idn> ormiret: Yeah, my JSON isn't great so that's probably poor understanding on my part. What should it be/
12:49 < ormiret> without the quotes would get bools
12:49 < jontyw> Yup
12:49 < jontyw> If this was YAML it would do the casting for you because YAML IS THE WORST
12:49 < idn> ormiret: Cool, I'll fix that up, thanks.
12:50 <@ms7821> and probabyl convert pass_mark into a time
12:52 < idn> ms7821: It's a percentage to go along with the pass_auto. If pass_auto is set and your result is greater than pass_mark then you passed the training.
12:52 <@ms7821> oh I mean yaml converts stuff to dates and times when you don't want it to
12:52 < idn> Oh!
12:52 < idn> Right, yes, with you.
12:53 <@ms7821> https://twitter.com/chrisjrn/status/1232016100038266880
12:54 < jonwood> And the state code for Ontario, Canada will be evaluated as `true`
12:54 <@ms7821> "The opposite of Ontario is Norway."
```

**Comment by idnorton** [comment]
So further discussion happened about where to put the file:
```
--- Day changed Fri Feb 28 2020
17:59 < idn> So I need to add some static JSON files to the repo for training, where should I put them? Directory off config or somewhere else?
17:59 < idn> Some/a
19:33 < jontyw> Config is fine
19:34 < jontyw> Or perhaps data/
20:29 <@ms7821> or even models/fixtures
20:30 <@ms7821> we'll move it if it's annoying, when it's annoying :)
20:30 <@ms7821> so don't worry :D
20:47 < jontyw> As with everything at EMF, just keep doing things until someone waves a flag and asks you to do it differently (or stop)
```
Consensus was `models/fixtures`.

**Comment by idnorton** [comment]
Missed adding notes here on bar training material:
```
16:44 < sde1000> This is the original text for the bar training: https://usercontent.irccloud-cdn.com/file/3LYiO0Er/Training%20outline.pdf
16:44 < sde1000> (It's in the Bar folder of the 2018 google drive, for those with access.)
16:45 < sde1000> Having it be part of our website is probably best, rather than having to integrate with a third-party site.
16:45 < sde1000> This doesn't need to be private.  The more people who know the answers the better!
```

**Comment by idnorton** [comment]
There exists a spreadsheet with the questions and answers for the bars training which is in the 2018 bars Google Drive folder. I don't believe I have the details or access to this but it was mentioned by @marksteward :
```
23:14 <@ms7821> there's an accompanying spreadsheet which I can share with anyone who's up for doing it in a way that doesn't involve putting that in git
```
Though further discussion it was agreed that we don't need this information to be private and can put it in the git repo.

**Comment by idnorton** [comment]
There are a total of 12 questions in the training material that need to be captured fully by the test. Currently there are only 5 and it needs to be clear that more will follow.

**Comment by ormiret** [comment]
Done with #1050
