### ISSUE TITLE
Shift signup broken

### ISSUE THREAD

**Issue by idnorton** [emfcamp/Website#868]
When attempting to sign up for a shift at http://127.0.0.1:5000/volunteer/schedule

We get an error:
```
Bad Request
The CSRF token is missing.
```

Likely a missing nonce as discussed on IRC:
```
15:12 < russss> idn: a bit more context there: the content-security-policy header restricts which javascript can be run, it's a security feature.
15:13 < russss> If you have an inline script (i.e. one in <script> tags), you need to either put a nonce attribute (using `nonce="{{csp_nonce}}"`) or permit the script 
                with a SHA hash of the content of the script tag.
```

**Comment by idnorton** [comment]
See also #869 as that's a blocker to progressing this

**Comment by russss** [comment]
Yeah, in this case the JS isn't running due to the content security policy. You need to add a `nonce="{{csp_nonce}}"` attribute to the inline <script> on that page.

**Comment by idnorton** [comment]
This has been fixed! Wooo!
