### ISSUE TITLE
Volunteer template errors `jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'assets'.`

### ISSUE THREAD

**Issue by idnorton** [emfcamp/Website#869]
Volunteer shift at http://127.0.0.1:5000/volunteer/schedule/ has this issue.

It's down to an issue with `template/volunteer/base.html` and deprecation of `ASSET_URL`.

Need to find and fix all instances of `ASSET_URL`

**Comment by idnorton** [comment]
Getting past the error in `volunteer/base.html` with the following diff:
```
diff --git templates/volunteer/base.html templates/volunteer/base.html
index 50223d5e..ed41bc40 100644
--- templates/volunteer/base.html
+++ templates/volunteer/base.html
@@ -5,8 +5,9 @@
         <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
         <meta name="viewport" content="width=device-width, initial-scale=1.0">
         <title>{% block title %}{% endblock %}{% if self.title() %} - {% endif %}EMF Volunteering</title>
-        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
-        <link rel="stylesheet" href="{{ static_url_for('static', filename='css/volunteer.css') }}">
+        {% block css %}                ￼
+           <link rel="stylesheet" href="{{ static_url_for('static', filename="css/main.css") }}">
+        {% endblock %}
         {% block head -%}{% endblock -%}
         <link rel="shortcut icon" href="/favicon.ico">
     </head>
@@ -39,11 +40,7 @@
     </div>
 </div>
 {% endblock %}
-<script src="//code.jquery.com/jquery-1.10.1.min.js"></script>
-<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
-{% assets "js_main" -%}
-<script src="{{ ASSET_URL }}"></script>
-{% endassets -%}
+<script src="{{static_url_for('static', filename="js/main.js")}}"></script>
 {% block foot -%}{% endblock -%}
 </body>
 </html>
```

Based on changes logged upstream at https://github.com/emfcamp/Website/commit/b1b46e9b48374f25e05dd548e9a61119ed348a5e

**Comment by idnorton** [comment]
PR has been merged but I want to confirm the specific example above is now working as expected.

**Comment by idnorton** [comment]
Check and confirm if there are other instances of this. Could be more bootstrap URLs, could be others.

Suggestions on how we find these? :)

**Comment by ormiret** [comment]
Couple other uses of `{% assets %}` to look at:
```
$ git grep "{% asset"
templates/arrivals/base.html:{% assets 'https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js',
templates/notification/base.html:    {# {% assets "css_admin" -%}
```

**Comment by idnorton** [comment]
Quick chat with @russss just now and this is http://localhost:5000/notify so I'll take a look at that next.

**Comment by idnorton** [comment]
This notify base URL should be under `volunteer/admin/` so this is a good point to shift this and use as a starting point for the notification epic. https://github.com/emfcamp/Website/issues/870

**Comment by russss** [comment]
I'd probably also change it to use the volunteer CSS rather than its own base template unless there's a good reason not to. I don't really understand why it's separate from the volunteer admin blueprint - it does seem to require the `volunteer:admin` permission.

**Comment by idnorton** [comment]
Trying to run before I can walk, so updating the existing notifications code so that it works before attempting to move it again.

**Comment by idnorton** [comment]
k, this ticket is done now. Further work on notifications should be happening in #870
