### ISSUE TITLE
Volunteer role signup - UI improvement

### ISSUE THREAD

**Issue by idnorton** [emfcamp/Website#947]
When signing up as a volunteer roles, a list is presented to select from. This does not look or feel great.

![image](https://user-images.githubusercontent.com/1237947/134977259-0eae2f3f-3d49-45d5-a653-c038b6b5b60d.png)

Review and suggest improvements on how we can make this a better user experience.

Additional considerations:

* Add other contact details - possibly a key/value pair table that will allow us to add arbitrary contact types
* Indicate available time periods of availability during the event. We need to decide what that might look like.

**Comment by jellybob** [comment]
This is now somewhat better, closing.
