### ISSUE TITLE
Schedule view - review and improve

### ISSUE THREAD

**Issue by idnorton** [emfcamp/Website#954]
Once #935 is done and working we need to look at and decide how we'd like to improve this.

**Comment by jellybob** [comment]
Thing one I'd suggest to improve this is for the admin mode which allows signing up any volunteer not to just give a select box drop down list of all volunteers - it works kind of ok with sample data, but I suspect will fall down hard with hundreds of registered volunteers.

I guess some sort of autocomplete, although I can't say I'm relishing implementing one that works reasonably.
