### ISSUE TITLE
Use X-Signature-SHA256 for wise

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#963]
This will require support from pywisetransfer

**Comment by marksteward** [comment]
While in the area, fix the 2FA and open issue.

**Comment by jayaddison** [comment]
Belatedly catching up on this @marksteward; I'm wondering if there's a minimal way to verify the `X-Signature-SHA256` header from the Wise HTTP event requests (e.g. something we could include soon and be relatively confident about, pending the refactor).

**Comment by marksteward** [comment]
Oh this isn't urgent (which is why I've sort of left the WIP refactor dangling). It's just that I expect Wise to deprecate and remove the old signature type at some point.

**Comment by jayaddison** [comment]
Don't take my word for it, but I _think_ that we can close this?

  * jayaddison/pywisetransfer#21
  * https://github.com/emfcamp/Website/blob/8766c5272037a986d1bc27bc604358b0a6155571/apps/payments/wise.py#L44-L48

**Comment by jayaddison** [comment]
(yep, I believe that this is resolved)

**Comment by marksteward** [comment]
Would be nice to move some more of the code into pywisetransfer (if our code is the right way to write a client it seems a bit involved), but yeah this is technically resolved.

**Comment by jayaddison** [comment]
Do you mean for the webhook handling in particular?  I think the JSON/data validation could certainly be moved into the library.

I haven't revisited it in a while but it could be time for a review.

**Comment by marksteward** [comment]
Yeah, and the bit where we have to [explicitly call](https://github.com/emfcamp/Website/blob/8766c52/apps/payments/wise.py#L37) `b64decode` so we know whether the exception is with the header or something else.

**Comment by jayaddison** [comment]
Ok - yep, I've taken another look at jayaddison/pywisetransfer#16 - I think I'll freshen that up and merge it soon.

One hesitation that I had (but didn't mention, evidently) is that I don't love binding the interface to `requests`, and would prefer to stay HTTP-library-agnostic.  Yeah, I realise almost everyone uses `requests`, but it's a principle thing.  Perhaps I can rename/refactor the function in a way that exposes a `requests`-specific helper function, leaving the core implementation agnostic.

A tiny detail in a way but I care about it.

**Comment by marksteward** [comment]
Probably not much consolation but aiohttp uses a similar interface https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.BaseRequest.json
